# Évaluation d'un système de recommandation My Content

Notebook pour entraîner et comparer plusieurs approches de recommandation sur le dataset Kaggle **news-portal-user-interactions-by-globocom**. L'objectif est de montrer clairement chaque étape (du chargement des données jusqu'au choix final du modèle).

> Ce notebook aligne désormais **toutes les approches de recommandation sur la bibliothèque Surprise** (https://surprise.readthedocs.io/) afin de bénéficier d'algorithmes collaboratifs standardisés et faciles à déployer.

In [1]:
# Imports & Config
from __future__ import annotations
import os
import pickle
import sys
import time
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd

pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_columns", None)

# Ensure the project root is importable
PROJECT_ROOT = Path('.').resolve().parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

# Configuration
CONFIG = {
    "clicks_dir": "../data/news-portal-user-interactions-by-globocom/clicks",
    "metadata_path": "../data/news-portal-user-interactions-by-globocom/articles_metadata.csv",
    "embeddings_path": "../data/news-portal-user-interactions-by-globocom/articles_embeddings.pickle",
    "max_click_files": None,
    "artifacts_dir": "../artifacts/evaluation",
    "k": 5,
    "random_seed": 42,
    "min_user_interactions": 3,
    "content_user_strategy": "last_item",
}
np.random.seed(CONFIG["random_seed"])
Path(CONFIG["artifacts_dir"]).mkdir(parents=True, exist_ok=True)
print("Config ready", CONFIG)

# Context columns provided in the clicks dataset
CONTEXT_COLUMNS = [
    "click_environment",
    "click_deviceGroup",
    "click_os",
    "click_country",
    "click_region",
    "click_referrer_type",
]

from surprise import Dataset, Reader, NormalPredictor, SVDpp

Config ready {'clicks_dir': '../data/news-portal-user-interactions-by-globocom/clicks', 'metadata_path': '../data/news-portal-user-interactions-by-globocom/articles_metadata.csv', 'embeddings_path': '../data/news-portal-user-interactions-by-globocom/articles_embeddings.pickle', 'max_click_files': None, 'artifacts_dir': '../artifacts/evaluation', 'k': 5, 'random_seed': 42, 'min_user_interactions': 3, 'content_user_strategy': 'last_item'}

## Contexte

Nous voulons proposer à chaque lecteur un Top-5 d'articles susceptibles de l'intéresser. Le notebook illustre la démarche de A à Z : préparation des données, construction de différentes familles de modèles puis comparaison à l'aide de métriques de ranking.

## Données

Les fichiers attendus sont situés dans `/data/*`.

In [2]:

# Load data utilities


def detect_timestamp_column(df: pd.DataFrame) -> str:
    """Detect the timestamp-like column name."""
    candidates = ["click_timestamp", "timestamp", "event_time", "ts", "time"]
    for col in df.columns:
        if col in candidates or col.lower() in candidates:
            return col
    raise ValueError("No timestamp-like column found. Expected one of: " + ",".join(candidates))


def detect_article_column(df: pd.DataFrame) -> str:
    """Detect the article/item column name."""
    candidates = ["click_article_id", "clicked_article_id", "article_id", "item_id", "content_id"]
    for col in df.columns:
        if col in candidates:
            return col
    raise ValueError("No article id column found. Expected one of: " + ",".join(candidates))


def infer_unix_unit(values: pd.Series) -> str:
    numeric = pd.to_numeric(values, errors="coerce").dropna()
    if numeric.empty:
        return "s"
    max_abs = numeric.abs().max()
    if max_abs >= 1e14:
        return "ns"
    if max_abs >= 1e11:
        return "ms"
    return "s"


def to_timestamp(series: pd.Series) -> pd.Series:
    if pd.api.types.is_datetime64_any_dtype(series):
        return pd.to_datetime(series)
    if pd.api.types.is_numeric_dtype(series):
        unit = infer_unix_unit(series)
        return pd.to_datetime(series, unit=unit, errors="coerce")

    converted = pd.to_datetime(series, errors="coerce")
    if converted.notna().any():
        return converted

    unit = infer_unix_unit(series)
    return pd.to_datetime(series, unit=unit, errors="coerce")


def list_click_files(path: Union[str, Path]) -> List[Path]:
    path_obj = Path(path)
    if path_obj.is_file():
        return [path_obj]
    if path_obj.is_dir():
        return sorted(path_obj.glob("clicks_hour_*.csv"))
    return []


def ensure_context_columns(df: pd.DataFrame) -> pd.DataFrame:
    """Ensure session_size and context columns exist with safe defaults."""
    df = df.copy()
    if "session_size" not in df.columns:
        df["session_size"] = 1
    for col in CONTEXT_COLUMNS:
        if col not in df.columns:
            df[col] = "unknown"
    return df


def create_synthetic_clicks(path: str, n_users: int = 50, n_items: int = 120, days: int = 30, interactions_per_user: int = 25) -> pd.DataFrame:
    """Create a small synthetic clicks dataset to keep the notebook runnable."""
    rng = np.random.default_rng(CONFIG["random_seed"])
    start = pd.Timestamp("2022-01-01")
    envs = ["web", "app"]
    devices = ["mobile", "desktop"]
    oss = ["ios", "android", "linux"]
    referrers = ["direct", "search", "social"]
    records = []
    for user in range(1, n_users + 1):
        offsets = rng.integers(0, days, size=interactions_per_user)
        timestamps = [start + pd.Timedelta(int(o), unit="D") for o in sorted(offsets.tolist())]
        articles = rng.integers(1, n_items + 1, size=interactions_per_user)
        for ts, art in zip(timestamps, articles):
            records.append({
                "user_id": int(user),
                "article_id": int(art),
                "timestamp": ts,
                "session_size": int(rng.integers(1, 6)),
                "click_environment": rng.choice(envs),
                "click_deviceGroup": rng.choice(devices),
                "click_os": rng.choice(oss),
                "click_country": rng.choice(["fr", "us", "br"]),
                "click_region": rng.choice(["idf", "sp", "ca"]),
                "click_referrer_type": rng.choice(referrers),
            })
    df = pd.DataFrame(records).sort_values("timestamp").reset_index(drop=True)
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(path, index=False)
    print(
        f"Synthetic clicks dataset created at {path} "
        f"(users={n_users}, items={n_items}, interactions={len(df)})"
    )
    return df


def load_clicks(path: str, max_files: Optional[int] = None) -> pd.DataFrame:
    """Load clicks data from the Globo hourly files, with a safety cap."""
    files = list_click_files(path)
    total_files = len(files)
    if not files:
        print(f"Clicks directory not found at {path}. Generating a synthetic sample for demonstration.")
        return ensure_context_columns(create_synthetic_clicks(Path(path) / "clicks_hour_000.csv"))

    if max_files is not None:
        print(f"Limite explicite max_files={max_files}, total détecté={total_files}")
        files = files[:max_files]

    print(f"Chargement de {len(files)} fichiers clicks (total détecté={total_files}, limite={max_files if max_files is not None else 'aucune'})")
    frames = []
    for file in files:
        df = pd.read_csv(file)
        ts_col = detect_timestamp_column(df)
        article_col = detect_article_column(df)
        df[ts_col] = to_timestamp(df[ts_col])
        df = df.rename(columns={ts_col: "timestamp", article_col: "article_id"})
        df = ensure_context_columns(df)
        keep_cols = [col for col in [
            "user_id",
            "article_id",
            "timestamp",
            "session_size",
            *CONTEXT_COLUMNS,
        ] if col in df.columns]
        frames.append(df[keep_cols])

    combined = pd.concat(frames, ignore_index=True)
    combined = combined.sort_values("timestamp").reset_index(drop=True)
    print(f"Clicks agrégés : {len(combined)} lignes, {combined['user_id'].nunique()} utilisateurs uniques, {combined['article_id'].nunique()} articles uniques.")
    return combined


def load_metadata(path: str) -> Optional[pd.DataFrame]:
    """Load article metadata if available."""
    if not os.path.exists(path):
        print(f"Metadata file not found at {path}. Utilisation du pipeline Surprise uniquement si les métadonnées sont absentes.")
        return None
    meta = pd.read_csv(path)
    if "article_id" not in meta.columns:
        print("Metadata missing 'article_id' column. Ignoring metadata.")
        return None
    return meta


clicks = load_clicks(CONFIG["clicks_dir"], max_files=CONFIG["max_click_files"])
metadata = load_metadata(CONFIG["metadata_path"])
print(clicks.head())
print("Metadata loaded:", metadata is not None)

Chargement de 385 fichiers clicks (total détecté=385, limite=aucune)
Clicks agrégés : 2988181 lignes, 322897 utilisateurs uniques, 46033 articles uniques.
  user_id article_id               timestamp session_size click_environment  \
0      59     234853 2017-10-01 03:00:00.026            2                 4
1      79     159359 2017-10-01 03:00:01.702            2                 4
2     154      96663 2017-10-01 03:00:04.207            2                 4
3     111     202436 2017-10-01 03:00:14.140            2                 4
4      70     119592 2017-10-01 03:00:18.863            3                 4

  click_deviceGroup click_os click_country click_region click_referrer_type
0                 3        2             1           21                   1
1                 3        2             1           13                   1
2                 3        2             1           25                   7
3                 3        2             1            9                   7
4                 3        2             1           13                   2
Metadata loaded: True

## Analyse exploratoire des données

Courte photographie des fichiers sources immédiatement après le chargement :
- nombre de lignes et noms de colonnes des clics
- volumes et intégrité des métadonnées articles
- dimensions et structure du fichier d'`articles_embeddings`.

In [3]:
# EDA rapide sur les données sources
import pickle
from pathlib import Path
from collections.abc import Mapping


def summarize_timestamps(series: pd.Series):
    series = pd.to_datetime(series)
    daily = series.dt.date.value_counts().sort_index().rename_axis("date").reset_index(name="nb_clicks")
    hourly = series.dt.hour.value_counts().sort_index().rename_axis("hour").reset_index(name="nb_clicks")
    return series.min(), series.max(), daily, hourly


def describe_structure(obj, prefix="embeddings", max_depth=4):
    entries = []

    def add_entry(path, value, note=None):
        entry = {"chemin": path, "type": type(value).__name__}
        if hasattr(value, "shape"):
            entry["shape"] = tuple(getattr(value, "shape"))
        elif hasattr(value, "__len__") and not isinstance(value, (str, bytes)):
            entry["len"] = len(value)
        if hasattr(value, "dtype"):
            entry["dtype"] = str(getattr(value, "dtype"))
        if note:
            entry["note"] = note
        if isinstance(value, np.ndarray) and value.dtype.names:
            entry["dtype_fields"] = list(value.dtype.names)
        if isinstance(value, np.ndarray) and value.ndim == 1 and len(value) > 0 and not isinstance(value[0], (np.ndarray, list, tuple, Mapping)):
            entry["exemple"] = repr(value[:3].tolist())
        entries.append(entry)

    def walk(value, path, depth):
        add_entry(path, value)
        if depth >= max_depth:
            return
        if isinstance(value, Mapping):
            for k, v in value.items():
                walk(v, f"{path}.{k}", depth + 1)
        elif isinstance(value, (list, tuple, np.ndarray)) and not isinstance(value, (str, bytes)):
            if len(value) > 0:
                walk(value[0], f"{path}[0]", depth + 1)

    walk(obj, prefix, 0)
    return entries


click_files = list_click_files(CONFIG["clicks_dir"])
print(f"Nombre total de fichiers clicks détectés: {len(click_files)}")
if not click_files:
    print("Aucun fichier clicks trouvé au chemin configuré. Vérifiez le téléchargement des données.")

files_for_eda = click_files[:2]
per_file_stats = []
for file in files_for_eda:
    df_file = pd.read_csv(file)
    ts_col = detect_timestamp_column(df_file)
    article_col = detect_article_column(df_file)
    timestamps = to_timestamp(df_file[ts_col])
    per_file_stats.append(
        {
            "fichier": file.name,
            "nb_lignes": len(df_file),
            "colonnes": ", ".join(df_file.columns),
            "articles_uniques": df_file[article_col].nunique(),
            "horodatage_min": timestamps.min(),
            "horodatage_max": timestamps.max(),
        }
    )
if per_file_stats:
    display(pd.DataFrame(per_file_stats))
else:
    print("Pas assez de fichiers pour réaliser une EDA détaillée par fichier.")

print("=== Clicks (agrégés) ===")
if clicks.empty:
    print("Aucun clic chargé. Vérifier le chemin ou augmenter max_click_files.")
else:
    clicks_summary = {
        "nb_lignes": len(clicks),
        "colonnes": ", ".join(clicks.columns),
        "utilisateurs_uniques": clicks['user_id'].nunique() if 'user_id' in clicks else None,
        "articles_uniques": clicks['article_id'].nunique() if 'article_id' in clicks else None,
    }
    display(pd.DataFrame([clicks_summary]))

    total_articles = None
    if metadata is not None and 'article_id' in metadata:
        total_articles = metadata['article_id'].nunique()
    elif 'article_id' in clicks:
        total_articles = clicks['article_id'].nunique()

    total_clients = clicks['user_id'].nunique() if 'user_id' in clicks else None
    print("Synthèse globale (articles / clients)")
    display(pd.DataFrame([{
        'nombre_total_articles': total_articles,
        'nombre_total_clients': total_clients,
    }]))

    ts_min, ts_max, daily, hourly = summarize_timestamps(clicks['timestamp'])
    display(pd.DataFrame([
        {
            'horodatage_min': ts_min,
            'horodatage_max': ts_max,
            'fenetre_jours': (ts_max - ts_min).days + 1,
        }
    ]))
    print("Répartition par jour (jusqu'à 10 premières valeurs)")
    display(daily.head(10))
    print("Répartition par heure (0-23)")
    display(hourly)

print("=== Métadonnées des articles ===")
if metadata is None:
    print("Aucun fichier metadata chargé.")
else:
    meta_summary = {
        "nb_articles": len(metadata),
        "colonnes": ", ".join(metadata.columns),
        "articles_uniques": metadata['article_id'].nunique() if 'article_id' in metadata else None,
    }
    display(pd.DataFrame([meta_summary]))
    missing = metadata.isna().sum().sort_values(ascending=False)
    display(missing.to_frame('valeurs_manquantes'))
    if 'created_at_ts' in metadata.columns:
        created = to_timestamp(metadata['created_at_ts'])
        display(pd.DataFrame([{'premier_article': created.min(), 'dernier_article': created.max()}]))
    if 'article_id' in metadata.columns:
        overlap = set(clicks['article_id'].unique()) if 'article_id' in clicks.columns else set()
        coverage = len(overlap & set(metadata['article_id'].unique()))
        print(f"Articles présents dans clicks et metadata: {coverage}")


print("=== Embeddings d'articles ===")
embeddings_path = Path(CONFIG['embeddings_path'])
if embeddings_path.exists():
    with embeddings_path.open('rb') as f:
        embeddings_obj = pickle.load(f)
    print(f"Type chargé: {type(embeddings_obj)}")

    def summarize_matrix(mat):
        stats = {
            'shape': getattr(mat, 'shape', None),
            'dtype': getattr(mat, 'dtype', None),
        }

        dim_values = []
        shape = getattr(mat, 'shape', None)
        if shape is not None and len(shape) >= 2:
            dim_values.append(shape[1])
        elif isinstance(mat, (list, tuple, np.ndarray)):
            for row in mat:
                if hasattr(row, '__len__') and not isinstance(row, (str, bytes)):
                    try:
                        dim_values.append(len(row))
                    except TypeError:
                        continue

        if dim_values:
            stats.update({
                'profondeur_min': min(dim_values),
                'profondeur_moyenne': float(np.mean(dim_values)),
                'profondeur_max': max(dim_values),
            })

        if hasattr(mat, 'shape') and len(getattr(mat, 'shape', [])) == 2:
            norms = np.linalg.norm(mat, axis=1)
            stats.update(
                {
                    'nb_vectors': mat.shape[0],
                    'dim': mat.shape[1],
                    'norm_min': norms.min(),
                    'norm_max': norms.max(),
                    'norm_moyenne': norms.mean(),
                }
            )
        return stats

    base_structure = describe_structure(embeddings_obj, max_depth=4)

    if isinstance(embeddings_obj, dict):
        keys = list(embeddings_obj.keys())
        print(f"Clés disponibles: {keys}")
        matrix = embeddings_obj.get('embeddings')
        ids = embeddings_obj.get('articles_ids') or embeddings_obj.get('article_ids')

        structure = base_structure.copy()
        if ids is not None:
            structure.insert(0, {
                'chemin': 'embeddings.article_ids',
                'type': type(ids).__name__,
                'len': len(ids),
                'note': "Identifiants d'articles fournis dans le fichier",
            })
        if structure:
            print("Structure détaillée de l'objet d'embeddings (par chemin de clé):")
            display(pd.DataFrame(structure))

        if matrix is not None:
            stats = summarize_matrix(matrix)
            stats.update(
                {
                    'colonnes': ", ".join(keys),
                    'nb_articles_ids': len(ids) if ids is not None else None,
                    'ids_uniques': len(set(ids)) if ids is not None else None,
                    'couverture_metadata': len(set(ids) & set(metadata['article_id']))
                    if (metadata is not None and ids is not None and 'article_id' in metadata)
                    else None,
                    'couverture_clicks': len(set(ids) & set(clicks['article_id']))
                    if (not clicks.empty and ids is not None and 'article_id' in clicks)
                    else None,
                }
            )
            display(pd.DataFrame([stats]))

            if ids is not None:
                sample_ids = ids[:5] if len(ids) >= 5 else ids
                print("Aperçu des premiers article_id liés aux embeddings:")
                display(pd.DataFrame({'article_id': sample_ids}))

            preview_cols = [f"emb_{i}" for i in range(min(5, matrix.shape[1] if hasattr(matrix, 'shape') else 0))]
            if preview_cols:
                preview = pd.DataFrame(matrix[:5, : len(preview_cols)], columns=preview_cols)
                if ids is not None:
                    preview.insert(0, 'article_id', ids[: len(preview)])
                print("Aperçu des embeddings (quelques colonnes et premières lignes):")
                display(preview)
                print("Colonnes affichées pour l'aperçu des embeddings:")
                print(", ".join(preview.columns))

                if ids is not None and metadata is not None and 'article_id' in metadata:
                    meta_cols = [c for c in ['title', 'category_id', 'created_at_ts', 'publisher'] if c in metadata.columns]
                    meta_sample = (
                        preview[['article_id']]
                        .merge(metadata[['article_id'] + meta_cols], on='article_id', how='left')
                    )
                    if 'created_at_ts' in meta_sample.columns:
                        meta_sample['created_at_ts'] = to_timestamp(meta_sample['created_at_ts'])
                    print("Exemple de liaison embedding -> metadata sur article_id (5 premières lignes):")
                    display(meta_sample.head())
        else:
            print("Aucune matrice d'embeddings explicite trouvée dans l'objet chargé.")
    elif hasattr(embeddings_obj, 'shape'):
        stats = summarize_matrix(embeddings_obj)

        inferred_ids = None
        mapping_note = None
        if metadata is not None and 'article_id' in metadata and hasattr(embeddings_obj, 'shape'):
            if embeddings_obj.shape[0] == len(metadata):
                inferred_ids = metadata['article_id'].reset_index(drop=True)
                mapping_note = (
                    "Aucun article_id explicite fourni ; association supposée alignée sur l'ordre des metadata."
                )
            else:
                mapping_note = (
                    "Aucun article_id dans le fichier d'embeddings et la taille ne correspond pas aux metadata : "
                    f"{embeddings_obj.shape[0]} vecteurs vs {len(metadata)} lignes de metadata."
                )
        else:
            mapping_note = (
                "Aucun identifiant d'article n'est présent dans le fichier d'embeddings (mapping externe requis)."
            )

        structure = base_structure.copy()
        if inferred_ids is not None:
            structure.insert(0, {
                'chemin': 'embeddings.article_id (inféré)',
                'type': type(inferred_ids).__name__,
                'len': len(inferred_ids),
                'note': "Alignement supposé sur metadata.article_id (index identique).",
            })
        if structure:
            print("Structure détaillée de l'objet d'embeddings (par chemin de clé):")
            display(pd.DataFrame(structure))

        if mapping_note:
            print(mapping_note)

        if inferred_ids is not None:
            stats.update(
                {
                    'ids_source': 'metadata.article_id (alignement par index)',
                    'ids_uniques': inferred_ids.nunique(),
                    'couverture_metadata': len(set(inferred_ids) & set(metadata['article_id'])),
                    'couverture_clicks': len(set(inferred_ids) & set(clicks['article_id'])) if not clicks.empty else None,
                }
            )

        display(pd.DataFrame([stats]))
        if len(getattr(embeddings_obj, 'shape', [])) >= 2 and embeddings_obj.shape[1] > 0:
            preview_cols = [f"emb_{i}" for i in range(min(5, embeddings_obj.shape[1]))]
            preview = pd.DataFrame(embeddings_obj[:5, : len(preview_cols)], columns=preview_cols)
            if inferred_ids is not None:
                preview.insert(0, 'article_id', inferred_ids.iloc[: len(preview)].values)
            print("Aperçu direct de la matrice d'embeddings:")
            display(preview)
            print("Colonnes affichées pour l'aperçu des embeddings:")
            print(", ".join(preview.columns))

            if inferred_ids is not None and metadata is not None:
                meta_cols = [c for c in ['title', 'category_id', 'created_at_ts', 'publisher'] if c in metadata.columns]
                meta_sample = preview[['article_id']].merge(
                    metadata[['article_id'] + meta_cols], on='article_id', how='left'
                )
                if 'created_at_ts' in meta_sample.columns:
                    meta_sample['created_at_ts'] = to_timestamp(meta_sample['created_at_ts'])
                print("Exemple de liaison embedding -> metadata sur article_id (inféré):")
                display(meta_sample.head())
        else:
            print("Objet chargé non structuré, utilisez type/len pour investiguer.")
else:
    print(f"Fichier d'embeddings introuvable à {embeddings_path}")

Nombre total de fichiers clicks détectés: 385

,fichier,nb_lignes,colonnes,articles_uniques,horodatage_min,horodatage_max
0,clicks_hour_000.csv,1883,"user_id, session_id, session_start, session_size, click_article_id, click_timestamp, click_environment, click_deviceGroup, click_os, click_country, click_region, click_referrer_type",323,2017-10-01 03:00:00.026,2017-10-03 02:35:54.157
1,clicks_hour_001.csv,1415,"user_id, session_id, session_start, session_size, click_article_id, click_timestamp, click_environment, click_deviceGroup, click_os, click_country, click_region, click_referrer_type",289,2017-10-01 03:36:28.615,2017-10-02 02:41:03.190

=== Clicks (agrégés) ===

,nb_lignes,colonnes,utilisateurs_uniques,articles_uniques
0,2988181,"user_id, article_id, timestamp, session_size, click_environment, click_deviceGroup, click_os, click_country, click_region, click_referrer_type",322897,46033

Synthèse globale (articles / clients)

   nombre_total_articles  nombre_total_clients
0                 364047                322897

           horodatage_min          horodatage_max  fenetre_jours
0 2017-10-01 03:00:00.026 2017-11-13 20:04:14.886             44

Répartition par jour (jusqu'à 10 premières valeurs)

         date  nb_clicks
0  2017-10-01      94056
1  2017-10-02     303177
2  2017-10-03     261159
3  2017-10-04     215415
4  2017-10-05     190003
5  2017-10-06     207646
6  2017-10-07     139323
7  2017-10-08     108110
8  2017-10-09     248208
9  2017-10-10     282391

Répartition par heure (0-23)

    hour  nb_clicks
0      0     126579
1      1     120741
2      2      94295
3      3      61811
4      4      32818
5      5      18562
6      6      14519
7      7      16630
8      8      32108
9      9      72840
10    10     129366
11    11     184429
12    12     161948
13    13     168764
14    14     182515
15    15     188017
16    16     201664
17    17     191439
18    18     190480
19    19     192220
20    20     180024
21    21     152294
22    22     141096
23    23     133022

=== Métadonnées des articles ===

,nb_articles,colonnes,articles_uniques
0,364047,"article_id, category_id, created_at_ts, publisher_id, words_count",364047

               valeurs_manquantes
article_id                      0
category_id                     0
created_at_ts                   0
publisher_id                    0
words_count                     0

      premier_article     dernier_article
0 2006-09-27 11:14:35 2018-03-13 12:12:30

Articles présents dans clicks et metadata: 46033
=== Embeddings d'articles ===
Type chargé: <class 'numpy.ndarray'>
Structure détaillée de l'objet d'embeddings (par chemin de clé):

,chemin,type,len,note,shape,dtype,exemple
0,embeddings.article_id (inféré),Series,364047.0,Alignement supposé sur metadata.article_id (index identique).,NaN,NaN,NaN
1,embeddings,ndarray,NaN,NaN,"(364047, 250)",float32,NaN
2,embeddings[0],ndarray,NaN,NaN,"(250,)",float32,"[-0.16118301451206207, -0.9572331309318542, -0.13794444501399994]"
3,embeddings[0][0],float32,NaN,NaN,(),float32,NaN

Aucun article_id explicite fourni ; association supposée alignée sur l'ordre des metadata.

,shape,dtype,profondeur_min,profondeur_moyenne,profondeur_max,nb_vectors,dim,norm_min,norm_max,norm_moyenne,ids_source,ids_uniques,couverture_metadata,couverture_clicks
0,"(364047, 250)",float32,250,250.0,250,364047,250,1.845483,11.18309,7.939456,metadata.article_id (alignement par index),364047,364047,46033

Aperçu direct de la matrice d'embeddings:

   article_id     emb_0     emb_1     emb_2     emb_3     emb_4
0           0 -0.161183 -0.957233 -0.137944  0.050855  0.830055
1           1 -0.523216 -0.974058  0.738608  0.155234  0.626294
2           2 -0.619619 -0.972960 -0.207360 -0.128861  0.044748
3           3 -0.740843 -0.975749  0.391698  0.641738 -0.268645
4           4 -0.279052 -0.972315  0.685374  0.113056  0.238315

Colonnes affichées pour l'aperçu des embeddings:
article_id, emb_0, emb_1, emb_2, emb_3, emb_4
Exemple de liaison embedding -> metadata sur article_id (inféré):

   article_id  category_id       created_at_ts
0           0            0 2017-12-13 05:53:39
1           1            1 2014-07-14 12:45:36
2           2            1 2014-08-22 00:35:06
3           3            1 2014-08-19 17:11:53
4           4            1 2014-08-03 13:06:11

# Article Embeddings

Ce fichier contient les **embeddings des articles**, c’est-à-dire une **représentation numérique du contenu**
permettant de comparer les articles entre eux sur le plan sémantique.

* **Format** : matrice NumPy `(N, D)` en `float32`
* **1 ligne = 1 article**
* **D colonnes = dimensions latentes**
* Les valeurs individuelles n’ont pas de signification directe

L’`article_id` n’est **pas toujours stocké explicitement** : lorsqu’il est présent, il faut **construire un mapping**
`article_id -> row_index`. Si les identifiants ne sont pas fournis, il est nécessaire d’utiliser un mapping externe
(par exemple un fichier associé) — **ne jamais supposer que l’index de ligne correspond à l’`article_id`**.

Les embeddings **ne sont pas normalisés** : la **similarité cosinus** est la mesure recommandée pour comparer les articles.

## Réduction de dimension des embeddings (PCA)

Objectif : réduire la taille des embeddings pour les publier et les charger plus rapidement (Azure Functions), tout en conservant un maximum de variance expliquée.

In [4]:
# PCA (ACP) sur les embeddings
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

# === Paramètres (à ajuster) ===
N_COMPONENTS = 32  # int (ex: 128) ou float (ex: 0.95)
APPLY_STANDARDIZATION = True

# === Chemins de sortie ===
OUTPUT_DIR = embeddings_path.parent if 'embeddings_path' in globals() else Path('.').resolve()
pca_suffix = str(N_COMPONENTS).replace('.', '_')
REDUCED_EMBEDDINGS_PATH = OUTPUT_DIR / f"articles_embeddings_pca_{pca_suffix}.npz"
PCA_MODEL_PATH = OUTPUT_DIR / f"pca_model_{pca_suffix}.pkl"

# === Récupération de la matrice d'embeddings ===
if 'embeddings_obj' not in globals():
    raise ValueError("embeddings_obj n'est pas chargé. Exécutez la cellule de chargement des embeddings.")

article_ids = None
if isinstance(embeddings_obj, dict):
    embeddings_matrix = embeddings_obj.get('embeddings')
    article_ids = embeddings_obj.get('articles_ids') or embeddings_obj.get('article_ids')
else:
    embeddings_matrix = embeddings_obj

if embeddings_matrix is None:
    raise ValueError("Impossible de trouver la matrice d'embeddings dans embeddings_obj.")

embeddings_matrix = np.asarray(embeddings_matrix)
print(f"Shape avant PCA: {embeddings_matrix.shape}")

# === Standardisation optionnelle ===
if APPLY_STANDARDIZATION:
    scaler = StandardScaler()
    embeddings_for_pca = scaler.fit_transform(embeddings_matrix)
else:
    embeddings_for_pca = embeddings_matrix

# === Choix du solveur ===
if isinstance(N_COMPONENTS, float):
    svd_solver = 'full'
else:
    svd_solver = 'randomized'

pca = PCA(n_components=N_COMPONENTS, random_state=42, svd_solver=svd_solver)
reduced_embeddings = pca.fit_transform(embeddings_for_pca)

print(f"Shape après PCA: {reduced_embeddings.shape}")
print("Variance expliquée cumulée:", round(float(pca.explained_variance_ratio_.cumsum()[-1]), 6))

# === Sauvegardes ===
if article_ids is not None:
    np.savez_compressed(REDUCED_EMBEDDINGS_PATH, embeddings=reduced_embeddings, article_ids=np.array(article_ids))
    print(f"Embeddings réduits + article_ids sauvegardés: {REDUCED_EMBEDDINGS_PATH}")
else:
    np.save(REDUCED_EMBEDDINGS_PATH.with_suffix('.npy'), reduced_embeddings)
    print(f"Embeddings réduits sauvegardés: {REDUCED_EMBEDDINGS_PATH.with_suffix('.npy')}")

with open(PCA_MODEL_PATH, 'wb') as f:
    pickle.dump(pca, f)
print(f"Modèle PCA sauvegardé: {PCA_MODEL_PATH}")

Shape avant PCA: (364047, 250)
Shape après PCA: (364047, 32)
Variance expliquée cumulée: 0.842911
Embeddings réduits sauvegardés: ../data/news-portal-user-interactions-by-globocom/articles_embeddings_pca_32.npy
Modèle PCA sauvegardé: ../data/news-portal-user-interactions-by-globocom/pca_model_32.pkl

## Préparation des données et split temporel

Les splits sont réalisés **par utilisateur**, en conservant l'ordre chronologique :
- historique utilisateur ordonné
- 1 interaction la plus récente pour le test
- 1 interaction juste avant pour la validation
- le reste pour l'entraînement

Cette stratégie garantit l'absence de fuite d'information tout en restant robuste pour des historiques courts.

In [5]:
# Data preparation utilities

def clean_interactions(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    df["user_id"] = pd.to_numeric(df["user_id"], errors="coerce")
    df["article_id"] = pd.to_numeric(df["article_id"], errors="coerce")
    df["timestamp"] = pd.to_datetime(df["timestamp"], errors="coerce")
    df = df.dropna(subset=["user_id", "article_id", "timestamp"])
    df["user_id"] = df["user_id"].astype(int)
    df["article_id"] = df["article_id"].astype(int)
    df = df.sort_values(["user_id", "timestamp"]).reset_index(drop=True)
    return df

def build_user_histories(df: pd.DataFrame) -> Dict[int, List[int]]:
    return (
        df.sort_values(["user_id", "timestamp"])
        .groupby("user_id")["article_id"]
        .apply(list)
        .to_dict()
    )

def temporal_split_per_user(df: pd.DataFrame, min_interactions: int = 3) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    train_rows = []
    val_rows = []
    test_rows = []
    for user_id, group in df.groupby("user_id"):
        group = group.sort_values("timestamp")
        if len(group) < min_interactions:
            continue
        test_rows.append(group.iloc[-1])
        val_rows.append(group.iloc[-2])
        if len(group) > 2:
            train_rows.append(group.iloc[:-2])
    train_df = pd.concat(train_rows, ignore_index=True) if train_rows else pd.DataFrame(columns=df.columns)
    val_df = pd.DataFrame(val_rows) if val_rows else pd.DataFrame(columns=df.columns)
    test_df = pd.DataFrame(test_rows) if test_rows else pd.DataFrame(columns=df.columns)
    return train_df, val_df, test_df

clicks_clean = clean_interactions(clicks)
user_histories = build_user_histories(clicks_clean)
train_df, val_df, test_df = temporal_split_per_user(clicks_clean, CONFIG["min_user_interactions"])

print(f"Interactions totales après nettoyage: {len(clicks_clean)}")
print(f"Train: {len(train_df)}, Validation: {len(val_df)}, Test: {len(test_df)}")

# Candidate items are derived from training data only
candidate_items = sorted(train_df["article_id"].unique().tolist())
print(f"Catalog (train only): {len(candidate_items)} items")

# Leakage checks
def assert_no_leakage(train_df: pd.DataFrame, val_df: pd.DataFrame, test_df: pd.DataFrame) -> None:
    """Ensure temporal ordering per user without forbidding repeated items."""
    latest_train = train_df.groupby("user_id")["timestamp"].max()
    earliest_val = val_df.groupby("user_id")["timestamp"].min()
    earliest_test = test_df.groupby("user_id")["timestamp"].min()
    for user_id in latest_train.index:
        if user_id in earliest_val.index:
            assert latest_train[user_id] <= earliest_val[user_id], "Temporal leakage train->val"
        if user_id in earliest_test.index:
            assert latest_train[user_id] <= earliest_test[user_id], "Temporal leakage train->test"

    if not val_df.empty and not test_df.empty:
        latest_val = val_df.groupby("user_id")["timestamp"].max()
        earliest_test = test_df.groupby("user_id")["timestamp"].min()
        for user_id in latest_val.index:
            if user_id in earliest_test.index:
                assert latest_val[user_id] <= earliest_test[user_id], "Temporal leakage val->test"

assert_no_leakage(train_df, val_df, test_df)

train_user_items = train_df.groupby("user_id")["article_id"].apply(set).to_dict()

print(f"Users in train: {len(train_user_items)}")

display(train_df.head())

Interactions totales après nettoyage: 2988181
Train: 2342387, Validation: 221469, Test: 221469
Catalog (train only): 36165 items
Users in train: 221469

,user_id,article_id,timestamp,session_size,click_environment,click_deviceGroup,click_os,click_country,click_region,click_referrer_type
0,0,157541,2017-10-01 03:00:28.020,2,4,3,20,1,20,2
1,0,68866,2017-10-01 03:00:58.020,2,4,3,20,1,20,2
2,0,96755,2017-10-07 01:33:53.155,2,4,3,20,1,20,2
3,0,313996,2017-10-07 01:34:23.155,2,4,3,20,1,20,2
4,0,160158,2017-10-07 14:54:50.915,2,4,3,20,1,20,2

## Modèles et métriques de ranking

Les modèles sont entraînés **indépendamment** et évalués sur le même jeu de candidats (articles vus en train).
Pour le modèle avec pondération de session, nous transformons le signal implicite en :
`rating = rating_base + log1p(session_size)` afin de renforcer légèrement les sessions plus longues.

Le **rating_base** est défini comme `1 + 0.01 * rang_normalisé` (rang temporel par utilisateur),
ce qui introduit une légère variance nécessaire au calcul des prédictions sans changer la logique implicite.

**Note** : les modèles SVD++ exploitent à la fois les notes implicites et l'historique d'interactions
pour apprendre des facteurs latents (pas de similarité de contenu textuel direct).

---

In [6]:
# Modeling and evaluation


def build_surprise_trainset(df: pd.DataFrame, rating_col: str) -> Tuple[Dataset, object]:
    reader = Reader(rating_scale=(1.0, 5.0))
    data = Dataset.load_from_df(df[["user_id", "article_id", rating_col]], reader)
    trainset = data.build_full_trainset()
    return data, trainset


from typing import Any, Dict, List, Tuple, Callable, Optional
import heapq
import multiprocessing as mp
import time
import numpy as np
import pandas as pd

# ----------------------------
# 1) Candidate generation
# ----------------------------
TOP_N_CANDIDATES = 5000  # tune: 2_000 / 5_000 / 10_000 / 20_000
popular_candidates: List[int] = (
    train_df.groupby("article_id")
    .size()
    .sort_values(ascending=False)
    .head(TOP_N_CANDIDATES)
    .index.astype(int)
    .tolist()
)

if not popular_candidates:
    popular_candidates = train_df["article_id"].dropna().astype(int).unique().tolist()


# ----------------------------
# 2) Fast recommenders
# ----------------------------

def recommend_random(rng: np.random.Generator, user_id: int, k: int) -> List[int]:
    seen = train_user_items.get(int(user_id), set())
    candidates = [item for item in popular_candidates if item not in seen]
    if not candidates:
        return []
    rng.shuffle(candidates)
    return candidates[:k]


def recommend_surprise_fast(model: Any, user_id: int, k: int) -> List[int]:
    """
    Score only a limited candidate pool (top-N popular items) to avoid O(all_items).
    Uses heapq.nlargest to avoid sorting the whole candidate list.
    """
    seen = train_user_items.get(int(user_id), set())
    candidates = [i for i in popular_candidates if i not in seen]
    if not candidates:
        return []

    scored: List[Tuple[int, float]] = []
    for item_id in candidates:
        est = float(model.predict(int(user_id), int(item_id)).est)
        scored.append((int(item_id), est))

    topk = heapq.nlargest(k, scored, key=lambda t: t[1])
    return [item_id for item_id, _ in topk]


def recommend_surprise(model: Any, user_id: int, k: int) -> List[int]:
    return recommend_surprise_fast(model, user_id, k)


def _jaccard_overlap(a: List[int], b: List[int], k: int) -> float:
    if k <= 0:
        return 0.0
    a_set = set(a[:k])
    b_set = set(b[:k])
    if not a_set and not b_set:
        return 0.0
    return len(a_set & b_set) / max(len(a_set | b_set), 1)


def _filter_candidates(
    items: List[int],
    seen: set,
    known_items: Optional[set] = None,
) -> Tuple[List[int], int, int]:
    filtered: List[int] = []
    filtered_seen = 0
    ignored_unknown = 0
    for item in items:
        if item in seen:
            filtered_seen += 1
            continue
        if known_items is not None and item not in known_items:
            ignored_unknown += 1
            continue
        if item in filtered:
            continue
        filtered.append(item)
    return filtered, filtered_seen, ignored_unknown


def recommend_hybrid_rank_fusion(
    user_id: int,
    k: int,
    weight_cf: float = 0.6,
    weight_cb: float = 0.4,
    debug: bool = False,
    top_n_debug: Optional[int] = None,
    prefer: str = "cf",
) -> List[int]:
    try:
        user_key = int(user_id)
    except (TypeError, ValueError):
        user_key = None
    seen = train_user_items.get(user_key, set()) if user_key is not None else set()

    list_len = max(k, top_n_debug or k)

    cf_raw = recommend_surprise(svdpp_weighted_model, user_id, list_len)
    cb_raw = recommend_content_based(user_id, list_len)

    known_items = set(candidate_items) if "candidate_items" in globals() else None

    cf_list, cf_seen_filtered, cf_unknown_filtered = _filter_candidates(cf_raw, seen, known_items)
    cb_list, cb_seen_filtered, cb_unknown_filtered = _filter_candidates(cb_raw, seen, known_items)

    total_seen_filtered = cf_seen_filtered + cb_seen_filtered
    total_unknown_filtered = cf_unknown_filtered + cb_unknown_filtered

    overlap_k = top_n_debug or k
    overlap = _jaccard_overlap(cb_list, cf_list, overlap_k)

    if debug:
        print(
            "[hybrid-rank] cb_raw={} cf_raw={} cb_filtered={} cf_filtered={} overlap@{}={:.2f} "
            "filtered_seen={} ignored_unknown={}".format(
                len(cb_raw),
                len(cf_raw),
                len(cb_list),
                len(cf_list),
                overlap_k,
                overlap,
                total_seen_filtered,
                total_unknown_filtered,
            ),
            flush=True,
        )

    if not cb_list and not cf_list:
        return build_fallback(seen, k)
    if not cb_list:
        return cf_list[:k]
    if not cf_list:
        return cb_list[:k]

    cf_scores: Dict[int, float] = {}
    for rank, item_id in enumerate(cf_list):
        cf_scores[item_id] = (1 - rank / max(len(cf_list), 1)) * float(weight_cf)

    cb_scores: Dict[int, float] = {}
    for rank, item_id in enumerate(cb_list):
        cb_scores[item_id] = (1 - rank / max(len(cb_list), 1)) * float(weight_cb)

    total_scores: Dict[int, float] = {}
    for item_id, score in cf_scores.items():
        total_scores[item_id] = total_scores.get(item_id, 0.0) + score
    for item_id, score in cb_scores.items():
        total_scores[item_id] = total_scores.get(item_id, 0.0) + score

    prefer_cf = prefer.lower() == "cf"
    cf_rank = {item_id: rank for rank, item_id in enumerate(cf_list)}
    cb_rank = {item_id: rank for rank, item_id in enumerate(cb_list)}

    def sort_key(item_id: int) -> Tuple[float, int, int]:
        score = total_scores[item_id]
        in_cf = item_id in cf_rank
        in_cb = item_id in cb_rank
        if prefer_cf:
            primary = 0 if in_cf else 1
        else:
            primary = 0 if in_cb else 1
        secondary = cf_rank.get(item_id, cb_rank.get(item_id, len(cb_list) + len(cf_list)))
        return (-score, primary, secondary)

    ranked = sorted(total_scores.keys(), key=sort_key)
    return ranked[:k]

# ----------------------------
# 3) Metrics
# ----------------------------

def precision_at_k(recommended: List[int], relevant: List[int], k: int) -> float:
    if not recommended:
        return 0.0
    recommended_k = recommended[:k]
    relevant_set = set(relevant)
    hits = sum(1 for item in recommended_k if item in relevant_set)
    return hits / k


def recall_at_k(recommended: List[int], relevant: List[int], k: int) -> float:
    if not relevant:
        return 0.0
    recommended_k = recommended[:k]
    relevant_set = set(relevant)
    hits = sum(1 for item in recommended_k if item in relevant_set)
    return hits / len(relevant_set)


def average_precision_at_k(recommended: List[int], relevant: List[int], k: int) -> float:
    if not relevant:
        return 0.0
    relevant_set = set(relevant)
    ap = 0.0
    hits = 0
    for idx, item in enumerate(recommended[:k], start=1):
        if item in relevant_set:
            hits += 1
            ap += hits / idx
    return ap / min(len(relevant_set), k)


def ndcg_at_k(recommended: List[int], relevant: List[int], k: int) -> float:
    if not relevant:
        return 0.0
    relevant_set = set(relevant)
    dcg = 0.0
    for idx, item in enumerate(recommended[:k], start=1):
        if item in relevant_set:
            dcg += 1.0 / np.log2(idx + 1)
    ideal_hits = min(len(relevant_set), k)
    idcg = sum(1.0 / np.log2(idx + 1) for idx in range(1, ideal_hits + 1))
    return dcg / idcg if idcg > 0 else 0.0



def rmse_from_predictions(predictions: List[float], targets: List[float]) -> float:
    if not predictions:
        return 0.0
    errors = np.subtract(np.array(predictions, dtype=float), np.array(targets, dtype=float))
    return float(np.sqrt(np.mean(errors ** 2)))


def score_rmse(
    predict_fn: Callable[[int, int], float],
    eval_df: pd.DataFrame,
    rating_col: str = "rating",
) -> float:
    if eval_df.empty or rating_col not in eval_df.columns:
        return 0.0
    predictions = []
    targets = []
    for row in eval_df.itertuples(index=False):
        predictions.append(float(predict_fn(int(row.user_id), int(row.article_id))))
        targets.append(float(getattr(row, rating_col)))
    return rmse_from_predictions(predictions, targets)


def make_predict_fn(model: Any) -> Callable[[int, int], float]:
    def _predict(user_id: int, item_id: int) -> float:
        prediction = model.predict(int(user_id), int(item_id))
        return float(getattr(prediction, "est", prediction))

    return _predict


# ----------------------------
# 4) Parallel evaluation helpers
# ----------------------------

_EVAL_RECOMMEND_FN = None
_EVAL_USER_RELEVANT = None
_EVAL_K = None


def _set_eval_globals(recommend_fn, user_relevant, k):
    global _EVAL_RECOMMEND_FN, _EVAL_USER_RELEVANT, _EVAL_K
    _EVAL_RECOMMEND_FN = recommend_fn
    _EVAL_USER_RELEVANT = user_relevant
    _EVAL_K = k


def _evaluate_user(user_id: int):
    relevant = _EVAL_USER_RELEVANT.get(int(user_id), [])
    user_start = time.perf_counter()
    recommended = _EVAL_RECOMMEND_FN(int(user_id), int(_EVAL_K))
    latency = time.perf_counter() - user_start
    return (
        {
            "precision": precision_at_k(recommended, relevant, _EVAL_K),
            "recall": recall_at_k(recommended, relevant, _EVAL_K),
            "map": average_precision_at_k(recommended, relevant, _EVAL_K),
            "ndcg": ndcg_at_k(recommended, relevant, _EVAL_K),
            "latency": float(latency),
        },
        recommended,
    )


def evaluate_model(
    model_name: str,
    recommend_fn: Callable[[int, int], List[int]],
    eval_df: pd.DataFrame,
    k: int,
    predict_fn: Optional[Callable[[int, int], float]] = None,
    rating_col: str = "rating",
    *,
    rmse_df: Optional[pd.DataFrame] = None,
    log_every: int = 2000,
    show_progress: bool = True,
    coverage_denominator: Optional[int] = None,
    parallel: bool = True,
    n_jobs: Optional[int] = 9,
) -> Dict[str, float]:
    """
    Retrocompatible replacement of your evaluate_model:
    - Same required signature and returned dict keys.
    - Adds optional progress logging (disabled by show_progress=False).
    - Allows overriding coverage denominator (defaults to len(popular_candidates) if available).
    - Enables multi-core evaluation when supported (parallel=True, n_jobs=None uses all cores).
    """


    start_time = time.perf_counter()
    per_user_metrics: List[Dict[str, float]] = []
    all_recommended: List[int] = []

    users = eval_df["user_id"].dropna().astype(int).unique().tolist()
    n_users = len(users)

    if coverage_denominator is None:
        coverage_denominator = max(len(popular_candidates), 1)

    if show_progress:
        print(f"▶ Evaluating: {model_name} | users={n_users} | k={k}", flush=True)


    rmse_source = rmse_df if rmse_df is not None else eval_df
    rmse = score_rmse(predict_fn, rmse_source, rating_col) if predict_fn is not None else None

    user_relevant = (
        eval_df.groupby("user_id")["article_id"]
        .apply(lambda s: s.dropna().astype(int).tolist())
        .to_dict()
    )

    use_parallel = parallel and n_users > 1
    ctx = None
    if use_parallel:
        available_methods = mp.get_all_start_methods()
        if "fork" in available_methods:
            ctx = mp.get_context("fork")
        else:
            use_parallel = False
            if show_progress:
                print("⚠️ Multiprocessing fork not available; falling back to sequential evaluation.")

    if use_parallel and ctx is not None:
        if n_jobs is None:
            n_jobs = ctx.cpu_count()
        n_jobs = max(1, min(int(n_jobs), n_users))
        chunksize = max(1, n_users // (n_jobs * 4))

        _set_eval_globals(recommend_fn, user_relevant, k)
        with ctx.Pool(
            processes=n_jobs,
        ) as pool:
            for idx, (metrics, recommended) in enumerate(
                pool.imap_unordered(_evaluate_user, users, chunksize=chunksize), start=1
            ):
                per_user_metrics.append(metrics)
                all_recommended.extend(recommended)

                if show_progress and (
                    idx == 1 or idx == n_users or (log_every > 0 and idx % log_every == 0)
                ):
                    elapsed = time.perf_counter() - start_time
                    avg_per_user = elapsed / max(idx, 1)
                    eta = avg_per_user * (n_users - idx)
                    print(
                        f"[{model_name}] {idx}/{n_users} ({idx/n_users:.1%}) "
                        f"elapsed={elapsed/60:.1f}min ETA={eta/60:.1f}min "
                        f"avg_latency={avg_per_user:.4f}s/user",
                        flush=True,
                    )
    else:
        for idx, user_id in enumerate(users, start=1):
            relevant = user_relevant.get(int(user_id), [])

            user_start = time.perf_counter()
            recommended = recommend_fn(int(user_id), int(k))
            latency = time.perf_counter() - user_start

            all_recommended.extend(recommended)

            per_user_metrics.append(
                {
                    "precision": precision_at_k(recommended, relevant, k),
                    "recall": recall_at_k(recommended, relevant, k),
                    "map": average_precision_at_k(recommended, relevant, k),
                    "ndcg": ndcg_at_k(recommended, relevant, k),
                    "latency": float(latency),
                }
            )

            if show_progress and (
                idx == 1 or idx == n_users or (log_every > 0 and idx % log_every == 0)
            ):
                elapsed = time.perf_counter() - start_time
                avg_per_user = elapsed / max(idx, 1)
                eta = avg_per_user * (n_users - idx)
                print(
                    f"[{model_name}] {idx}/{n_users} ({idx/n_users:.1%}) "
                    f"elapsed={elapsed/60:.1f}min ETA={eta/60:.1f}min "
                    f"avg_latency={avg_per_user:.4f}s/user",
                    flush=True,
                )

    total_time = time.perf_counter() - start_time

    if not per_user_metrics:
        result = {
            "model": model_name,
            "precision@k": 0.0,
            "recall@k": 0.0,
            "map@k": 0.0,
            "ndcg@k": 0.0,
            "coverage@k": 0.0,
            "latency_per_user_s": 0.0,
            "total_eval_time_s": float(total_time),
        }
        if rmse is not None:
            result["rmse"] = float(rmse)
        return result

    metrics_df = pd.DataFrame(per_user_metrics)
    coverage = len(set(all_recommended)) / max(int(coverage_denominator), 1)

    if show_progress:
        print(
            f"✔ Done: {model_name} in {total_time/60:.1f}min | "
            f"mean_latency={metrics_df['latency'].mean():.4f}s/user | "
            f"coverage={coverage:.4f}",
            flush=True,
        )

    result = {
        "model": model_name,
        "precision@k": float(metrics_df["precision"].mean()),
        "recall@k": float(metrics_df["recall"].mean()),
        "map@k": float(metrics_df["map"].mean()),
        "ndcg@k": float(metrics_df["ndcg"].mean()),
        "coverage@k": float(coverage),
        "latency_per_user_s": float(metrics_df["latency"].mean()),
        "total_eval_time_s": float(total_time),
    }
    if rmse is not None:
        result["rmse"] = float(rmse)
    return result


# Prepare implicit ratings from training clicks
train_ratings_df = (
    train_df.groupby(["user_id", "article_id"], as_index=False)
    .agg(click_count=("article_id", "size"), avg_session_size=("session_size", "mean"))
)
# 1) build a less-compressed implicit score
train_ratings_df["implicit_score"] = (
    3.0 * np.log1p(train_ratings_df["click_count"].astype(float))
    + 1.0 * np.log1p(train_ratings_df["avg_session_size"].astype(float))
)

# 2) robust scaling: clip to p95 to avoid outliers dominating
p95_train = float(np.percentile(train_ratings_df["implicit_score"].values, 95))
train_ratings_df["implicit_score_clipped"] = np.clip(train_ratings_df["implicit_score"].values, None, p95_train)

# 3) min-max scale to [1, 5]
min_s = float(train_ratings_df["implicit_score_clipped"].min())
max_s = float(train_ratings_df["implicit_score_clipped"].max())
if max_s > min_s:
    train_ratings_df["rating"] = 1.0 + 4.0 * (train_ratings_df["implicit_score_clipped"] - min_s) / (max_s - min_s)
else:
    train_ratings_df["rating"] = 1.0

# keep these for TEST scaling
TRAIN_SCALE = {"min_s": min_s, "max_s": max_s, "p95": p95_train}


p95_session = float(np.percentile(train_ratings_df["avg_session_size"].values, 95))
if p95_session > 0:
    train_ratings_df["session_weight"] = (
        np.log1p(train_ratings_df["avg_session_size"].astype(float))
        / np.log1p(p95_session)
    ).clip(0.0, 1.0)
else:
    train_ratings_df["session_weight"] = 0.0

train_ratings_df["rating_weighted"] = np.clip(
    train_ratings_df["rating"] * (1.0 + train_ratings_df["session_weight"]),
    1.0,
    5.0,
)

train_ratings_df = train_ratings_df[["user_id", "article_id", "rating", "rating_weighted", "avg_session_size"]].astype(
    {
        "user_id": int,
        "article_id": int,
        "rating": float,
        "rating_weighted": float,
        "avg_session_size": float,
    }
)


# Ratings for RMSE on held-out interactions
test_ratings_df = (
    test_df.groupby(["user_id", "article_id"], as_index=False)
    .agg(click_count=("article_id", "size"), avg_session_size=("session_size", "mean"))
)
# same implicit score transform as TRAIN
test_ratings_df["implicit_score"] = (
    3.0 * np.log1p(test_ratings_df["click_count"].astype(float))
    + 1.0 * np.log1p(test_ratings_df["avg_session_size"].astype(float))
)

# clip using TRAIN p95
test_ratings_df["implicit_score_clipped"] = np.clip(
    test_ratings_df["implicit_score"].values, None, float(TRAIN_SCALE["p95"])
)

# scale to [1, 5] using TRAIN min/max
min_s = float(TRAIN_SCALE["min_s"])
max_s = float(TRAIN_SCALE["max_s"])
if max_s > min_s:
    test_ratings_df["rating"] = 1.0 + 4.0 * (test_ratings_df["implicit_score_clipped"] - min_s) / (max_s - min_s)
else:
    test_ratings_df["rating"] = 1.0


test_ratings_df = test_ratings_df[["user_id", "article_id", "rating"]].astype(
    {"user_id": int, "article_id": int, "rating": float}
)


_, trainset_basic = build_surprise_trainset(train_ratings_df, rating_col="rating")
_, trainset_weighted = build_surprise_trainset(train_ratings_df, rating_col="rating_weighted")

# Models
rng = np.random.default_rng(CONFIG["random_seed"])

print(train_ratings_df["rating"].describe())
print(test_ratings_df["rating"].describe())

print("TRAIN rating:", train_ratings_df["rating"].min(), train_ratings_df["rating"].max())
print("TEST rating :", test_ratings_df["rating"].min(), test_ratings_df["rating"].max())

count    2.308505e+06
mean     2.211438e+00
std      1.213807e+00
min      1.000000e+00
25%      1.000000e+00
50%      1.830075e+00
75%      3.000000e+00
max      5.000000e+00
Name: rating, dtype: float64
count    221469.000000
mean          1.564063
std           0.768080
min           1.000000
25%           1.000000
50%           1.000000
75%           1.830075
max           5.000000
Name: rating, dtype: float64
TRAIN rating: 1.0 5.0
TEST rating : 1.0 5.0

In [7]:
# Train NormalPredictor baseline
normal_model = NormalPredictor()
normal_model.fit(trainset_basic)

In [8]:
# Train content-based cosine model on precomputed embeddings
from collections import namedtuple

def l2_normalize_rows(matrix: np.ndarray) -> np.ndarray:
    if matrix.size == 0:
        return matrix
    norms = np.linalg.norm(matrix, axis=1, keepdims=True)
    norms[norms == 0] = 1.0
    return matrix / norms

def extract_embeddings(obj):
    if obj is None:
        return None, None
    if isinstance(obj, dict):
        matrix = None
        for key in ("embeddings", "vectors", "item_embeddings", "matrix"):
            if key in obj and obj.get(key) is not None:
                matrix = obj.get(key)
                break
        article_ids = obj.get("articles_ids") or obj.get("article_ids")
        return matrix, article_ids
    return obj, None

embeddings_matrix, embeddings_article_ids = extract_embeddings(
    embeddings_obj if "embeddings_obj" in globals() else None
)

if embeddings_matrix is None:
    embeddings_matrix = np.empty((0, 0), dtype=float)

embeddings_matrix = np.asarray(embeddings_matrix)
if embeddings_matrix.ndim != 2:
    print("⚠️ Embeddings invalides: la matrice doit être 2D.")
    embeddings_matrix = np.empty((0, 0), dtype=float)

if embeddings_article_ids is None:
    print("⚠️ Aucun article_id trouvé dans les embeddings; mapping explicite requis.")
    embeddings_article_ids = []

if embeddings_article_ids and len(embeddings_article_ids) != embeddings_matrix.shape[0]:
    min_len = min(len(embeddings_article_ids), embeddings_matrix.shape[0])
    print(
        f"⚠️ Mismatch ids/embeddings: {len(embeddings_article_ids)} ids vs {embeddings_matrix.shape[0]} vectors. "
        f"Troncature à {min_len}."
    )
    embeddings_article_ids = list(embeddings_article_ids)[:min_len]
    embeddings_matrix = embeddings_matrix[:min_len]

item_index = {}
item_ids = []
for idx, raw_id in enumerate(embeddings_article_ids):
    try:
        if pd.isna(raw_id):
            continue
    except Exception:
        pass
    try:
        article_id = int(raw_id)
    except (TypeError, ValueError):
        continue
    if article_id in item_index:
        continue
    item_index[article_id] = idx
    item_ids.append(article_id)

item_vectors = l2_normalize_rows(embeddings_matrix) if item_index else np.empty((0, 0), dtype=float)
item_ids = [item_id for item_id in candidate_items if item_id in item_index]

popular_items = train_df["article_id"].value_counts().index.astype(int).tolist()

def build_fallback(seen: set, k: int) -> List[int]:
    if not popular_items:
        return []
    candidates = [item for item in popular_items if item not in seen]
    if not candidates:
        return popular_items[:k]
    return candidates[:k]

user_last_item = (
    train_df.sort_values("timestamp")
    .groupby("user_id")["article_id"]
    .last()
    .astype(int)
    .to_dict()
)

user_mean_profiles = {}
if item_index and item_vectors.size:
    for user_id, group in train_df.groupby("user_id"):
        clicked_ids = [item for item in group["article_id"].tolist() if item in item_index]
        if not clicked_ids:
            continue
        vectors = item_vectors[[item_index[item] for item in clicked_ids]]
        mean_vector = vectors.mean(axis=0)
        norm = np.linalg.norm(mean_vector)
        if norm == 0:
            continue
        user_mean_profiles[int(user_id)] = mean_vector / norm

content_user_strategy = CONFIG.get("content_user_strategy", "last_item")

Prediction = namedtuple("Prediction", ["est"])


class ContentBasedModel:
    def __init__(self, item_vectors, item_index, user_last_item, user_mean_profiles, strategy):
        self.item_vectors = item_vectors
        self.item_index = item_index
        self.user_last_item = user_last_item
        self.user_mean_profiles = user_mean_profiles
        self.strategy = strategy

    def _user_vector(self, user_id: int):
        if not self.item_index or self.item_vectors.size == 0:
            return None
        try:
            user_key = int(user_id)
        except (TypeError, ValueError):
            return None
        if self.strategy == "last_item":
            last_item_id = self.user_last_item.get(user_key)
            if last_item_id is None:
                return None
            idx = self.item_index.get(int(last_item_id))
            return None if idx is None else self.item_vectors[idx]
        if self.strategy == "mean_profile":
            return self.user_mean_profiles.get(user_key)
        return None

    def score(self, user_id, item_id) -> float:
        user_vector = self._user_vector(user_id)
        try:
            item_key = int(item_id)
        except (TypeError, ValueError):
            return 0.0
        idx = self.item_index.get(item_key)
        if user_vector is None or idx is None:
            return 0.0
        if self.item_vectors.shape[1] != user_vector.shape[0]:
            return 0.0
        return float(self.item_vectors[idx].dot(user_vector))

    def predict(self, user_id, item_id):
        return Prediction(est=self.score(user_id, item_id))


content_model = ContentBasedModel(
    item_vectors, item_index, user_last_item, user_mean_profiles, content_user_strategy
)


def recommend_content_based(user_id: int, k: int, strategy: str = content_user_strategy) -> List[int]:
    try:
        user_key = int(user_id)
    except (TypeError, ValueError):
        user_key = None
    seen = train_user_items.get(user_key, set()) if user_key is not None else set()

    if not item_index or item_vectors.size == 0:
        return build_fallback(seen, k)

    if strategy == "last_item":
        last_item_id = user_last_item.get(user_key) if user_key is not None else None
        if last_item_id is None:
            return build_fallback(seen, k)
        idx = item_index.get(int(last_item_id))
        if idx is None:
            return build_fallback(seen, k)
        user_vector = item_vectors[idx]
    elif strategy == "mean_profile":
        user_vector = user_mean_profiles.get(user_key) if user_key is not None else None
        if user_vector is None:
            return build_fallback(seen, k)
    else:
        return build_fallback(seen, k)

    if item_vectors.shape[1] != user_vector.shape[0]:
        return build_fallback(seen, k)

    candidate_ids = [item for item in item_ids if item not in seen]
    if not candidate_ids:
        return build_fallback(seen, k)

    candidate_idx = [item_index[item] for item in candidate_ids]
    scores = item_vectors[candidate_idx].dot(user_vector)
    top_idx = np.argsort(scores)[::-1][:k]
    return [candidate_ids[i] for i in top_idx]

⚠️ Aucun article_id trouvé dans les embeddings; mapping explicite requis.

In [9]:
# Train SVD++ collaborative filtering model
svdpp_model = SVDpp(random_state=CONFIG["random_seed"])
svdpp_model.fit(trainset_basic)

In [10]:
# Train SVD++ model with session weighting
svdpp_weighted_model = SVDpp(random_state=CONFIG["random_seed"])
svdpp_weighted_model.fit(trainset_weighted)

In [11]:
results = []

results.append(
    evaluate_model(
        "NormalPredictor (topN popular candidates)",
        lambda user_id, k: recommend_surprise_fast(normal_model, user_id, k),
        test_df,
        CONFIG["k"],
        predict_fn=make_predict_fn(normal_model),
        rmse_df=test_ratings_df,
    )
)

▶ Evaluating: NormalPredictor (topN popular candidates) | users=221469 | k=5
[NormalPredictor (topN popular candidates)] 1/221469 (0.0%) elapsed=1.6min ETA=351303.6min avg_latency=95.1750s/user
[NormalPredictor (topN popular candidates)] 2000/221469 (0.9%) elapsed=1.6min ETA=174.1min avg_latency=0.0476s/user
[NormalPredictor (topN popular candidates)] 4000/221469 (1.8%) elapsed=1.6min ETA=86.2min avg_latency=0.0238s/user
[NormalPredictor (topN popular candidates)] 6000/221469 (2.7%) elapsed=1.6min ETA=57.0min avg_latency=0.0159s/user
[NormalPredictor (topN popular candidates)] 8000/221469 (3.6%) elapsed=1.6min ETA=42.6min avg_latency=0.0120s/user
[NormalPredictor (topN popular candidates)] 10000/221469 (4.5%) elapsed=1.6min ETA=33.8min avg_latency=0.0096s/user
[NormalPredictor (topN popular candidates)] 12000/221469 (5.4%) elapsed=1.6min ETA=27.9min avg_latency=0.0080s/user
[NormalPredictor (topN popular candidates)] 14000/221469 (6.3%) elapsed=1.6min ETA=23.8min avg_latency=0.0069s/user
[NormalPredictor (topN popular candidates)] 16000/221469 (7.2%) elapsed=1.6min ETA=20.6min avg_latency=0.0060s/user
[NormalPredictor (topN popular candidates)] 18000/221469 (8.1%) elapsed=1.6min ETA=18.1min avg_latency=0.0054s/user
[NormalPredictor (topN popular candidates)] 20000/221469 (9.0%) elapsed=1.6min ETA=16.3min avg_latency=0.0048s/user
[NormalPredictor (topN popular candidates)] 22000/221469 (9.9%) elapsed=1.6min ETA=14.6min avg_latency=0.0044s/user
[NormalPredictor (topN popular candidates)] 24000/221469 (10.8%) elapsed=1.6min ETA=13.3min avg_latency=0.0040s/user
[NormalPredictor (topN popular candidates)] 26000/221469 (11.7%) elapsed=1.6min ETA=12.1min avg_latency=0.0037s/user
[NormalPredictor (topN popular candidates)] 28000/221469 (12.6%) elapsed=1.6min ETA=11.2min avg_latency=0.0035s/user
[NormalPredictor (topN popular candidates)] 30000/221469 (13.5%) elapsed=1.6min ETA=10.3min avg_latency=0.0032s/user
[NormalPredictor (topN popular candidates)] 32000/221469 (14.4%) elapsed=1.7min ETA=9.8min avg_latency=0.0031s/user
[NormalPredictor (topN popular candidates)] 34000/221469 (15.4%) elapsed=1.7min ETA=9.1min avg_latency=0.0029s/user
[NormalPredictor (topN popular candidates)] 36000/221469 (16.3%) elapsed=1.7min ETA=8.5min avg_latency=0.0028s/user
[NormalPredictor (topN popular candidates)] 38000/221469 (17.2%) elapsed=1.7min ETA=8.0min avg_latency=0.0026s/user
[NormalPredictor (topN popular candidates)] 40000/221469 (18.1%) elapsed=1.7min ETA=7.5min avg_latency=0.0025s/user
[NormalPredictor (topN popular candidates)] 42000/221469 (19.0%) elapsed=1.7min ETA=7.1min avg_latency=0.0024s/user
[NormalPredictor (topN popular candidates)] 44000/221469 (19.9%) elapsed=1.7min ETA=6.7min avg_latency=0.0023s/user
[NormalPredictor (topN popular candidates)] 46000/221469 (20.8%) elapsed=1.7min ETA=6.3min avg_latency=0.0022s/user
[NormalPredictor (topN popular candidates)] 48000/221469 (21.7%) elapsed=1.7min ETA=6.0min avg_latency=0.0021s/user
[NormalPredictor (topN popular candidates)] 50000/221469 (22.6%) elapsed=1.7min ETA=5.7min avg_latency=0.0020s/user
[NormalPredictor (topN popular candidates)] 52000/221469 (23.5%) elapsed=1.7min ETA=5.4min avg_latency=0.0019s/user
[NormalPredictor (topN popular candidates)] 54000/221469 (24.4%) elapsed=1.7min ETA=5.2min avg_latency=0.0018s/user
[NormalPredictor (topN popular candidates)] 56000/221469 (25.3%) elapsed=3.0min ETA=9.0min avg_latency=0.0033s/user
[NormalPredictor (topN popular candidates)] 58000/221469 (26.2%) elapsed=3.0min ETA=8.6min avg_latency=0.0032s/user
[NormalPredictor (topN popular candidates)] 60000/221469 (27.1%) elapsed=3.0min ETA=8.2min avg_latency=0.0030s/user
[NormalPredictor (topN popular candidates)] 62000/221469 (28.0%) elapsed=3.1min ETA=7.9min avg_latency=0.0030s/user
[NormalPredictor (topN popular candidates)] 64000/221469 (28.9%) elapsed=3.1min ETA=7.6min avg_latency=0.0029s/user
[NormalPredictor (topN popular candidates)] 66000/221469 (29.8%) elapsed=3.1min ETA=7.2min avg_latency=0.0028s/user
[NormalPredictor (topN popular candidates)] 68000/221469 (30.7%) elapsed=3.1min ETA=7.0min avg_latency=0.0027s/user
[NormalPredictor (topN popular candidates)] 70000/221469 (31.6%) elapsed=3.1min ETA=6.7min avg_latency=0.0026s/user
[NormalPredictor (topN popular candidates)] 72000/221469 (32.5%) elapsed=3.1min ETA=6.4min avg_latency=0.0026s/user
[NormalPredictor (topN popular candidates)] 74000/221469 (33.4%) elapsed=3.1min ETA=6.1min avg_latency=0.0025s/user
[NormalPredictor (topN popular candidates)] 76000/221469 (34.3%) elapsed=3.1min ETA=5.9min avg_latency=0.0024s/user
[NormalPredictor (topN popular candidates)] 78000/221469 (35.2%) elapsed=3.1min ETA=5.7min avg_latency=0.0024s/user
[NormalPredictor (topN popular candidates)] 80000/221469 (36.1%) elapsed=3.1min ETA=5.5min avg_latency=0.0023s/user
[NormalPredictor (topN popular candidates)] 82000/221469 (37.0%) elapsed=3.1min ETA=5.3min avg_latency=0.0023s/user
[NormalPredictor (topN popular candidates)] 84000/221469 (37.9%) elapsed=3.1min ETA=5.1min avg_latency=0.0022s/user
[NormalPredictor (topN popular candidates)] 86000/221469 (38.8%) elapsed=3.1min ETA=4.9min avg_latency=0.0022s/user
[NormalPredictor (topN popular candidates)] 88000/221469 (39.7%) elapsed=3.1min ETA=4.7min avg_latency=0.0021s/user
[NormalPredictor (topN popular candidates)] 90000/221469 (40.6%) elapsed=3.1min ETA=4.6min avg_latency=0.0021s/user
[NormalPredictor (topN popular candidates)] 92000/221469 (41.5%) elapsed=3.1min ETA=4.4min avg_latency=0.0020s/user
[NormalPredictor (topN popular candidates)] 94000/221469 (42.4%) elapsed=3.1min ETA=4.3min avg_latency=0.0020s/user
[NormalPredictor (topN popular candidates)] 96000/221469 (43.3%) elapsed=3.1min ETA=4.1min avg_latency=0.0020s/user
[NormalPredictor (topN popular candidates)] 98000/221469 (44.2%) elapsed=3.1min ETA=4.0min avg_latency=0.0019s/user
[NormalPredictor (topN popular candidates)] 100000/221469 (45.2%) elapsed=3.1min ETA=3.8min avg_latency=0.0019s/user
[NormalPredictor (topN popular candidates)] 102000/221469 (46.1%) elapsed=3.1min ETA=3.7min avg_latency=0.0019s/user
[NormalPredictor (topN popular candidates)] 104000/221469 (47.0%) elapsed=3.1min ETA=3.6min avg_latency=0.0018s/user
[NormalPredictor (topN popular candidates)] 106000/221469 (47.9%) elapsed=3.2min ETA=3.4min avg_latency=0.0018s/user
[NormalPredictor (topN popular candidates)] 108000/221469 (48.8%) elapsed=3.2min ETA=3.3min avg_latency=0.0018s/user
[NormalPredictor (topN popular candidates)] 110000/221469 (49.7%) elapsed=3.2min ETA=3.2min avg_latency=0.0017s/user
[NormalPredictor (topN popular candidates)] 112000/221469 (50.6%) elapsed=4.5min ETA=4.4min avg_latency=0.0024s/user
[NormalPredictor (topN popular candidates)] 114000/221469 (51.5%) elapsed=4.5min ETA=4.3min avg_latency=0.0024s/user
[NormalPredictor (topN popular candidates)] 116000/221469 (52.4%) elapsed=4.5min ETA=4.1min avg_latency=0.0023s/user
[NormalPredictor (topN popular candidates)] 118000/221469 (53.3%) elapsed=4.6min ETA=4.0min avg_latency=0.0023s/user
[NormalPredictor (topN popular candidates)] 120000/221469 (54.2%) elapsed=4.6min ETA=3.9min avg_latency=0.0023s/user
[NormalPredictor (topN popular candidates)] 122000/221469 (55.1%) elapsed=4.6min ETA=3.7min avg_latency=0.0023s/user
[NormalPredictor (topN popular candidates)] 124000/221469 (56.0%) elapsed=4.6min ETA=3.6min avg_latency=0.0022s/user
[NormalPredictor (topN popular candidates)] 126000/221469 (56.9%) elapsed=4.6min ETA=3.5min avg_latency=0.0022s/user
[NormalPredictor (topN popular candidates)] 128000/221469 (57.8%) elapsed=4.6min ETA=3.4min avg_latency=0.0022s/user
[NormalPredictor (topN popular candidates)] 130000/221469 (58.7%) elapsed=4.6min ETA=3.2min avg_latency=0.0021s/user
[NormalPredictor (topN popular candidates)] 132000/221469 (59.6%) elapsed=4.6min ETA=3.1min avg_latency=0.0021s/user
[NormalPredictor (topN popular candidates)] 134000/221469 (60.5%) elapsed=4.6min ETA=3.0min avg_latency=0.0021s/user
[NormalPredictor (topN popular candidates)] 136000/221469 (61.4%) elapsed=4.6min ETA=2.9min avg_latency=0.0020s/user
[NormalPredictor (topN popular candidates)] 138000/221469 (62.3%) elapsed=4.6min ETA=2.8min avg_latency=0.0020s/user
[NormalPredictor (topN popular candidates)] 140000/221469 (63.2%) elapsed=4.6min ETA=2.7min avg_latency=0.0020s/user
[NormalPredictor (topN popular candidates)] 142000/221469 (64.1%) elapsed=4.7min ETA=2.6min avg_latency=0.0020s/user
[NormalPredictor (topN popular candidates)] 144000/221469 (65.0%) elapsed=4.7min ETA=2.5min avg_latency=0.0019s/user
[NormalPredictor (topN popular candidates)] 146000/221469 (65.9%) elapsed=4.7min ETA=2.4min avg_latency=0.0019s/user
[NormalPredictor (topN popular candidates)] 148000/221469 (66.8%) elapsed=4.7min ETA=2.3min avg_latency=0.0019s/user
[NormalPredictor (topN popular candidates)] 150000/221469 (67.7%) elapsed=4.7min ETA=2.2min avg_latency=0.0019s/user
[NormalPredictor (topN popular candidates)] 152000/221469 (68.6%) elapsed=4.7min ETA=2.1min avg_latency=0.0018s/user
[NormalPredictor (topN popular candidates)] 154000/221469 (69.5%) elapsed=4.8min ETA=2.1min avg_latency=0.0019s/user
[NormalPredictor (topN popular candidates)] 156000/221469 (70.4%) elapsed=4.8min ETA=2.0min avg_latency=0.0018s/user
[NormalPredictor (topN popular candidates)] 158000/221469 (71.3%) elapsed=4.8min ETA=1.9min avg_latency=0.0018s/user
[NormalPredictor (topN popular candidates)] 160000/221469 (72.2%) elapsed=4.8min ETA=1.8min avg_latency=0.0018s/user
[NormalPredictor (topN popular candidates)] 162000/221469 (73.1%) elapsed=4.8min ETA=1.8min avg_latency=0.0018s/user
[NormalPredictor (topN popular candidates)] 164000/221469 (74.1%) elapsed=4.8min ETA=1.7min avg_latency=0.0018s/user
[NormalPredictor (topN popular candidates)] 166000/221469 (75.0%) elapsed=4.8min ETA=1.6min avg_latency=0.0017s/user
[NormalPredictor (topN popular candidates)] 168000/221469 (75.9%) elapsed=6.0min ETA=1.9min avg_latency=0.0021s/user
[NormalPredictor (topN popular candidates)] 170000/221469 (76.8%) elapsed=6.0min ETA=1.8min avg_latency=0.0021s/user
[NormalPredictor (topN popular candidates)] 172000/221469 (77.7%) elapsed=6.0min ETA=1.7min avg_latency=0.0021s/user
[NormalPredictor (topN popular candidates)] 174000/221469 (78.6%) elapsed=6.1min ETA=1.7min avg_latency=0.0021s/user
[NormalPredictor (topN popular candidates)] 176000/221469 (79.5%) elapsed=6.1min ETA=1.6min avg_latency=0.0021s/user
[NormalPredictor (topN popular candidates)] 178000/221469 (80.4%) elapsed=6.1min ETA=1.5min avg_latency=0.0020s/user
[NormalPredictor (topN popular candidates)] 180000/221469 (81.3%) elapsed=6.1min ETA=1.4min avg_latency=0.0020s/user
[NormalPredictor (topN popular candidates)] 182000/221469 (82.2%) elapsed=6.1min ETA=1.3min avg_latency=0.0020s/user
[NormalPredictor (topN popular candidates)] 184000/221469 (83.1%) elapsed=6.1min ETA=1.2min avg_latency=0.0020s/user
[NormalPredictor (topN popular candidates)] 186000/221469 (84.0%) elapsed=6.1min ETA=1.2min avg_latency=0.0020s/user
[NormalPredictor (topN popular candidates)] 188000/221469 (84.9%) elapsed=6.1min ETA=1.1min avg_latency=0.0019s/user
[NormalPredictor (topN popular candidates)] 190000/221469 (85.8%) elapsed=6.1min ETA=1.0min avg_latency=0.0019s/user
[NormalPredictor (topN popular candidates)] 192000/221469 (86.7%) elapsed=6.1min ETA=0.9min avg_latency=0.0019s/user
[NormalPredictor (topN popular candidates)] 194000/221469 (87.6%) elapsed=6.1min ETA=0.9min avg_latency=0.0019s/user
[NormalPredictor (topN popular candidates)] 196000/221469 (88.5%) elapsed=6.1min ETA=0.8min avg_latency=0.0019s/user
[NormalPredictor (topN popular candidates)] 198000/221469 (89.4%) elapsed=6.1min ETA=0.7min avg_latency=0.0019s/user
[NormalPredictor (topN popular candidates)] 200000/221469 (90.3%) elapsed=6.1min ETA=0.7min avg_latency=0.0018s/user
[NormalPredictor (topN popular candidates)] 202000/221469 (91.2%) elapsed=6.1min ETA=0.6min avg_latency=0.0018s/user
[NormalPredictor (topN popular candidates)] 204000/221469 (92.1%) elapsed=6.1min ETA=0.5min avg_latency=0.0018s/user
[NormalPredictor (topN popular candidates)] 206000/221469 (93.0%) elapsed=6.1min ETA=0.5min avg_latency=0.0018s/user
[NormalPredictor (topN popular candidates)] 208000/221469 (93.9%) elapsed=6.1min ETA=0.4min avg_latency=0.0018s/user
[NormalPredictor (topN popular candidates)] 210000/221469 (94.8%) elapsed=6.2min ETA=0.3min avg_latency=0.0018s/user
[NormalPredictor (topN popular candidates)] 212000/221469 (95.7%) elapsed=6.2min ETA=0.3min avg_latency=0.0018s/user
[NormalPredictor (topN popular candidates)] 214000/221469 (96.6%) elapsed=6.2min ETA=0.2min avg_latency=0.0017s/user
[NormalPredictor (topN popular candidates)] 216000/221469 (97.5%) elapsed=6.2min ETA=0.2min avg_latency=0.0017s/user
[NormalPredictor (topN popular candidates)] 218000/221469 (98.4%) elapsed=6.2min ETA=0.1min avg_latency=0.0017s/user
[NormalPredictor (topN popular candidates)] 220000/221469 (99.3%) elapsed=6.2min ETA=0.0min avg_latency=0.0017s/user
[NormalPredictor (topN popular candidates)] 221469/221469 (100.0%) elapsed=6.2min ETA=0.0min avg_latency=0.0017s/user
✔ Done: NormalPredictor (topN popular candidates) in 6.2min | mean_latency=0.0145s/user | coverage=0.3148

In [12]:
# Train hybrid model (rank-based fusion of SVD++ session-weighted + content-based)
hybrid_weight_cf = 0.6
hybrid_weight_cb = 0.4

In [13]:


results.append(
    evaluate_model(
        "Random recommender",
        lambda user_id, k: recommend_random(rng, user_id, k),
        test_df,
        CONFIG["k"],
    )
)

▶ Evaluating: Random recommender | users=221469 | k=5
[Random recommender] 1/221469 (0.0%) elapsed=0.2min ETA=41938.1min avg_latency=11.3619s/user
[Random recommender] 2000/221469 (0.9%) elapsed=0.2min ETA=20.8min avg_latency=0.0057s/user
[Random recommender] 4000/221469 (1.8%) elapsed=0.2min ETA=10.3min avg_latency=0.0028s/user
[Random recommender] 6000/221469 (2.7%) elapsed=0.2min ETA=6.8min avg_latency=0.0019s/user
[Random recommender] 8000/221469 (3.6%) elapsed=0.2min ETA=5.1min avg_latency=0.0014s/user
[Random recommender] 10000/221469 (4.5%) elapsed=0.2min ETA=4.0min avg_latency=0.0011s/user
[Random recommender] 12000/221469 (5.4%) elapsed=0.2min ETA=3.3min avg_latency=0.0010s/user
[Random recommender] 14000/221469 (6.3%) elapsed=0.2min ETA=2.8min avg_latency=0.0008s/user
[Random recommender] 16000/221469 (7.2%) elapsed=0.2min ETA=2.4min avg_latency=0.0007s/user
[Random recommender] 18000/221469 (8.1%) elapsed=0.2min ETA=2.2min avg_latency=0.0006s/user
[Random recommender] 20000/221469 (9.0%) elapsed=0.2min ETA=1.9min avg_latency=0.0006s/user
[Random recommender] 22000/221469 (9.9%) elapsed=0.2min ETA=1.7min avg_latency=0.0005s/user
[Random recommender] 24000/221469 (10.8%) elapsed=0.2min ETA=1.6min avg_latency=0.0005s/user
[Random recommender] 26000/221469 (11.7%) elapsed=0.2min ETA=1.4min avg_latency=0.0004s/user
[Random recommender] 28000/221469 (12.6%) elapsed=0.2min ETA=1.3min avg_latency=0.0004s/user
[Random recommender] 30000/221469 (13.5%) elapsed=0.2min ETA=1.2min avg_latency=0.0004s/user
[Random recommender] 32000/221469 (14.4%) elapsed=0.2min ETA=1.1min avg_latency=0.0004s/user
[Random recommender] 34000/221469 (15.4%) elapsed=0.2min ETA=1.1min avg_latency=0.0003s/user
[Random recommender] 36000/221469 (16.3%) elapsed=0.2min ETA=1.0min avg_latency=0.0003s/user
[Random recommender] 38000/221469 (17.2%) elapsed=0.2min ETA=0.9min avg_latency=0.0003s/user
[Random recommender] 40000/221469 (18.1%) elapsed=0.2min ETA=0.9min avg_latency=0.0003s/user
[Random recommender] 42000/221469 (19.0%) elapsed=0.2min ETA=0.8min avg_latency=0.0003s/user
[Random recommender] 44000/221469 (19.9%) elapsed=0.2min ETA=0.8min avg_latency=0.0003s/user
[Random recommender] 46000/221469 (20.8%) elapsed=0.2min ETA=0.7min avg_latency=0.0003s/user
[Random recommender] 48000/221469 (21.7%) elapsed=0.2min ETA=0.7min avg_latency=0.0002s/user
[Random recommender] 50000/221469 (22.6%) elapsed=0.2min ETA=0.7min avg_latency=0.0002s/user
[Random recommender] 52000/221469 (23.5%) elapsed=0.2min ETA=0.6min avg_latency=0.0002s/user
[Random recommender] 54000/221469 (24.4%) elapsed=0.2min ETA=0.6min avg_latency=0.0002s/user
[Random recommender] 56000/221469 (25.3%) elapsed=0.2min ETA=0.6min avg_latency=0.0002s/user
[Random recommender] 58000/221469 (26.2%) elapsed=0.2min ETA=0.6min avg_latency=0.0002s/user
[Random recommender] 60000/221469 (27.1%) elapsed=0.2min ETA=0.6min avg_latency=0.0002s/user
[Random recommender] 62000/221469 (28.0%) elapsed=0.2min ETA=0.6min avg_latency=0.0002s/user
[Random recommender] 64000/221469 (28.9%) elapsed=0.2min ETA=0.5min avg_latency=0.0002s/user
[Random recommender] 66000/221469 (29.8%) elapsed=0.2min ETA=0.5min avg_latency=0.0002s/user
[Random recommender] 68000/221469 (30.7%) elapsed=0.2min ETA=0.5min avg_latency=0.0002s/user
[Random recommender] 70000/221469 (31.6%) elapsed=0.2min ETA=0.5min avg_latency=0.0002s/user
[Random recommender] 72000/221469 (32.5%) elapsed=0.2min ETA=0.5min avg_latency=0.0002s/user
[Random recommender] 74000/221469 (33.4%) elapsed=0.2min ETA=0.4min avg_latency=0.0002s/user
[Random recommender] 76000/221469 (34.3%) elapsed=0.2min ETA=0.4min avg_latency=0.0002s/user
[Random recommender] 78000/221469 (35.2%) elapsed=0.2min ETA=0.4min avg_latency=0.0002s/user
[Random recommender] 80000/221469 (36.1%) elapsed=0.2min ETA=0.4min avg_latency=0.0002s/user
[Random recommender] 82000/221469 (37.0%) elapsed=0.2min ETA=0.4min avg_latency=0.0002s/user
[Random recommender] 84000/221469 (37.9%) elapsed=0.2min ETA=0.4min avg_latency=0.0002s/user
[Random recommender] 86000/221469 (38.8%) elapsed=0.2min ETA=0.4min avg_latency=0.0002s/user
[Random recommender] 88000/221469 (39.7%) elapsed=0.2min ETA=0.3min avg_latency=0.0002s/user
[Random recommender] 90000/221469 (40.6%) elapsed=0.2min ETA=0.3min avg_latency=0.0001s/user
[Random recommender] 92000/221469 (41.5%) elapsed=0.2min ETA=0.3min avg_latency=0.0001s/user
[Random recommender] 94000/221469 (42.4%) elapsed=0.2min ETA=0.3min avg_latency=0.0001s/user
[Random recommender] 96000/221469 (43.3%) elapsed=0.2min ETA=0.3min avg_latency=0.0001s/user
[Random recommender] 98000/221469 (44.2%) elapsed=0.2min ETA=0.3min avg_latency=0.0001s/user
[Random recommender] 100000/221469 (45.2%) elapsed=0.2min ETA=0.3min avg_latency=0.0001s/user
[Random recommender] 102000/221469 (46.1%) elapsed=0.2min ETA=0.3min avg_latency=0.0001s/user
[Random recommender] 104000/221469 (47.0%) elapsed=0.2min ETA=0.3min avg_latency=0.0001s/user
[Random recommender] 106000/221469 (47.9%) elapsed=0.3min ETA=0.3min avg_latency=0.0001s/user
[Random recommender] 108000/221469 (48.8%) elapsed=0.3min ETA=0.3min avg_latency=0.0001s/user
[Random recommender] 110000/221469 (49.7%) elapsed=0.3min ETA=0.3min avg_latency=0.0001s/user
[Random recommender] 112000/221469 (50.6%) elapsed=0.3min ETA=0.3min avg_latency=0.0001s/user
[Random recommender] 114000/221469 (51.5%) elapsed=0.3min ETA=0.2min avg_latency=0.0001s/user
[Random recommender] 116000/221469 (52.4%) elapsed=0.3min ETA=0.2min avg_latency=0.0001s/user
[Random recommender] 118000/221469 (53.3%) elapsed=0.3min ETA=0.2min avg_latency=0.0001s/user
[Random recommender] 120000/221469 (54.2%) elapsed=0.3min ETA=0.2min avg_latency=0.0001s/user
[Random recommender] 122000/221469 (55.1%) elapsed=0.3min ETA=0.2min avg_latency=0.0001s/user
[Random recommender] 124000/221469 (56.0%) elapsed=0.3min ETA=0.2min avg_latency=0.0001s/user
[Random recommender] 126000/221469 (56.9%) elapsed=0.3min ETA=0.2min avg_latency=0.0001s/user
[Random recommender] 128000/221469 (57.8%) elapsed=0.3min ETA=0.2min avg_latency=0.0001s/user
[Random recommender] 130000/221469 (58.7%) elapsed=0.3min ETA=0.2min avg_latency=0.0001s/user
[Random recommender] 132000/221469 (59.6%) elapsed=0.3min ETA=0.2min avg_latency=0.0001s/user
[Random recommender] 134000/221469 (60.5%) elapsed=0.3min ETA=0.2min avg_latency=0.0001s/user
[Random recommender] 136000/221469 (61.4%) elapsed=0.3min ETA=0.2min avg_latency=0.0001s/user
[Random recommender] 138000/221469 (62.3%) elapsed=0.3min ETA=0.2min avg_latency=0.0001s/user
[Random recommender] 140000/221469 (63.2%) elapsed=0.3min ETA=0.2min avg_latency=0.0001s/user
[Random recommender] 142000/221469 (64.1%) elapsed=0.3min ETA=0.1min avg_latency=0.0001s/user
[Random recommender] 144000/221469 (65.0%) elapsed=0.3min ETA=0.1min avg_latency=0.0001s/user
[Random recommender] 146000/221469 (65.9%) elapsed=0.3min ETA=0.1min avg_latency=0.0001s/user
[Random recommender] 148000/221469 (66.8%) elapsed=0.3min ETA=0.1min avg_latency=0.0001s/user
[Random recommender] 150000/221469 (67.7%) elapsed=0.3min ETA=0.1min avg_latency=0.0001s/user
[Random recommender] 152000/221469 (68.6%) elapsed=0.3min ETA=0.1min avg_latency=0.0001s/user
[Random recommender] 154000/221469 (69.5%) elapsed=0.3min ETA=0.1min avg_latency=0.0001s/user
[Random recommender] 156000/221469 (70.4%) elapsed=0.3min ETA=0.1min avg_latency=0.0001s/user
[Random recommender] 158000/221469 (71.3%) elapsed=0.3min ETA=0.1min avg_latency=0.0001s/user
[Random recommender] 160000/221469 (72.2%) elapsed=0.3min ETA=0.1min avg_latency=0.0001s/user
[Random recommender] 162000/221469 (73.1%) elapsed=0.3min ETA=0.1min avg_latency=0.0001s/user
[Random recommender] 164000/221469 (74.1%) elapsed=0.3min ETA=0.1min avg_latency=0.0001s/user
[Random recommender] 166000/221469 (75.0%) elapsed=0.3min ETA=0.1min avg_latency=0.0001s/user
[Random recommender] 168000/221469 (75.9%) elapsed=0.3min ETA=0.1min avg_latency=0.0001s/user
[Random recommender] 170000/221469 (76.8%) elapsed=0.3min ETA=0.1min avg_latency=0.0001s/user
[Random recommender] 172000/221469 (77.7%) elapsed=0.3min ETA=0.1min avg_latency=0.0001s/user
[Random recommender] 174000/221469 (78.6%) elapsed=0.3min ETA=0.1min avg_latency=0.0001s/user
[Random recommender] 176000/221469 (79.5%) elapsed=0.3min ETA=0.1min avg_latency=0.0001s/user
[Random recommender] 178000/221469 (80.4%) elapsed=0.3min ETA=0.1min avg_latency=0.0001s/user
[Random recommender] 180000/221469 (81.3%) elapsed=0.3min ETA=0.1min avg_latency=0.0001s/user
[Random recommender] 182000/221469 (82.2%) elapsed=0.3min ETA=0.1min avg_latency=0.0001s/user
[Random recommender] 184000/221469 (83.1%) elapsed=0.3min ETA=0.1min avg_latency=0.0001s/user
[Random recommender] 186000/221469 (84.0%) elapsed=0.3min ETA=0.1min avg_latency=0.0001s/user
[Random recommender] 188000/221469 (84.9%) elapsed=0.3min ETA=0.1min avg_latency=0.0001s/user
[Random recommender] 190000/221469 (85.8%) elapsed=0.3min ETA=0.0min avg_latency=0.0001s/user
[Random recommender] 192000/221469 (86.7%) elapsed=0.3min ETA=0.0min avg_latency=0.0001s/user
[Random recommender] 194000/221469 (87.6%) elapsed=0.3min ETA=0.0min avg_latency=0.0001s/user
[Random recommender] 196000/221469 (88.5%) elapsed=0.3min ETA=0.0min avg_latency=0.0001s/user
[Random recommender] 198000/221469 (89.4%) elapsed=0.3min ETA=0.0min avg_latency=0.0001s/user
[Random recommender] 200000/221469 (90.3%) elapsed=0.3min ETA=0.0min avg_latency=0.0001s/user
[Random recommender] 202000/221469 (91.2%) elapsed=0.3min ETA=0.0min avg_latency=0.0001s/user
[Random recommender] 204000/221469 (92.1%) elapsed=0.3min ETA=0.0min avg_latency=0.0001s/user
[Random recommender] 206000/221469 (93.0%) elapsed=0.3min ETA=0.0min avg_latency=0.0001s/user
[Random recommender] 208000/221469 (93.9%) elapsed=0.3min ETA=0.0min avg_latency=0.0001s/user
[Random recommender] 210000/221469 (94.8%) elapsed=0.3min ETA=0.0min avg_latency=0.0001s/user
[Random recommender] 212000/221469 (95.7%) elapsed=0.3min ETA=0.0min avg_latency=0.0001s/user
[Random recommender] 214000/221469 (96.6%) elapsed=0.3min ETA=0.0min avg_latency=0.0001s/user
[Random recommender] 216000/221469 (97.5%) elapsed=0.3min ETA=0.0min avg_latency=0.0001s/user
[Random recommender] 218000/221469 (98.4%) elapsed=0.3min ETA=0.0min avg_latency=0.0001s/user
[Random recommender] 220000/221469 (99.3%) elapsed=0.3min ETA=0.0min avg_latency=0.0001s/user
[Random recommender] 221469/221469 (100.0%) elapsed=0.3min ETA=0.0min avg_latency=0.0001s/user
✔ Done: Random recommender in 0.3min | mean_latency=0.0003s/user | coverage=1.0000

In [14]:
results.append(
    evaluate_model(
        "Content-Based (cosine on embeddings)",
        lambda user_id, k: recommend_content_based(user_id, k),
        test_df,
        CONFIG["k"],
    )
)

▶ Evaluating: Content-Based (cosine on embeddings) | users=221469 | k=5
[Content-Based (cosine on embeddings)] 1/221469 (0.0%) elapsed=0.3min ETA=63841.1min avg_latency=17.2958s/user
[Content-Based (cosine on embeddings)] 2000/221469 (0.9%) elapsed=0.3min ETA=31.6min avg_latency=0.0086s/user
[Content-Based (cosine on embeddings)] 4000/221469 (1.8%) elapsed=0.3min ETA=15.7min avg_latency=0.0043s/user
[Content-Based (cosine on embeddings)] 6000/221469 (2.7%) elapsed=0.3min ETA=10.4min avg_latency=0.0029s/user
[Content-Based (cosine on embeddings)] 8000/221469 (3.6%) elapsed=0.3min ETA=7.7min avg_latency=0.0022s/user
[Content-Based (cosine on embeddings)] 10000/221469 (4.5%) elapsed=0.3min ETA=6.1min avg_latency=0.0017s/user
[Content-Based (cosine on embeddings)] 12000/221469 (5.4%) elapsed=0.3min ETA=5.0min avg_latency=0.0014s/user
[Content-Based (cosine on embeddings)] 14000/221469 (6.3%) elapsed=0.3min ETA=4.3min avg_latency=0.0012s/user
[Content-Based (cosine on embeddings)] 16000/221469 (7.2%) elapsed=0.3min ETA=3.7min avg_latency=0.0011s/user
[Content-Based (cosine on embeddings)] 18000/221469 (8.1%) elapsed=0.3min ETA=3.3min avg_latency=0.0010s/user
[Content-Based (cosine on embeddings)] 20000/221469 (9.0%) elapsed=0.3min ETA=2.9min avg_latency=0.0009s/user
[Content-Based (cosine on embeddings)] 22000/221469 (9.9%) elapsed=0.3min ETA=2.6min avg_latency=0.0008s/user
[Content-Based (cosine on embeddings)] 24000/221469 (10.8%) elapsed=0.3min ETA=2.4min avg_latency=0.0007s/user
[Content-Based (cosine on embeddings)] 26000/221469 (11.7%) elapsed=0.3min ETA=2.2min avg_latency=0.0007s/user
[Content-Based (cosine on embeddings)] 28000/221469 (12.6%) elapsed=0.3min ETA=2.0min avg_latency=0.0006s/user
[Content-Based (cosine on embeddings)] 30000/221469 (13.5%) elapsed=0.3min ETA=1.9min avg_latency=0.0006s/user
[Content-Based (cosine on embeddings)] 32000/221469 (14.4%) elapsed=0.3min ETA=1.7min avg_latency=0.0005s/user
[Content-Based (cosine on embeddings)] 34000/221469 (15.4%) elapsed=0.3min ETA=1.6min avg_latency=0.0005s/user
[Content-Based (cosine on embeddings)] 36000/221469 (16.3%) elapsed=0.3min ETA=1.5min avg_latency=0.0005s/user
[Content-Based (cosine on embeddings)] 38000/221469 (17.2%) elapsed=0.3min ETA=1.4min avg_latency=0.0005s/user
[Content-Based (cosine on embeddings)] 40000/221469 (18.1%) elapsed=0.3min ETA=1.3min avg_latency=0.0004s/user
[Content-Based (cosine on embeddings)] 42000/221469 (19.0%) elapsed=0.3min ETA=1.2min avg_latency=0.0004s/user
[Content-Based (cosine on embeddings)] 44000/221469 (19.9%) elapsed=0.3min ETA=1.2min avg_latency=0.0004s/user
[Content-Based (cosine on embeddings)] 46000/221469 (20.8%) elapsed=0.3min ETA=1.1min avg_latency=0.0004s/user
[Content-Based (cosine on embeddings)] 48000/221469 (21.7%) elapsed=0.3min ETA=1.1min avg_latency=0.0004s/user
[Content-Based (cosine on embeddings)] 50000/221469 (22.6%) elapsed=0.3min ETA=1.0min avg_latency=0.0004s/user
[Content-Based (cosine on embeddings)] 52000/221469 (23.5%) elapsed=0.3min ETA=1.0min avg_latency=0.0003s/user
[Content-Based (cosine on embeddings)] 54000/221469 (24.4%) elapsed=0.3min ETA=0.9min avg_latency=0.0003s/user
[Content-Based (cosine on embeddings)] 56000/221469 (25.3%) elapsed=0.4min ETA=1.2min avg_latency=0.0004s/user
[Content-Based (cosine on embeddings)] 58000/221469 (26.2%) elapsed=0.4min ETA=1.2min avg_latency=0.0004s/user
[Content-Based (cosine on embeddings)] 60000/221469 (27.1%) elapsed=0.4min ETA=1.1min avg_latency=0.0004s/user
[Content-Based (cosine on embeddings)] 62000/221469 (28.0%) elapsed=0.4min ETA=1.1min avg_latency=0.0004s/user
[Content-Based (cosine on embeddings)] 64000/221469 (28.9%) elapsed=0.4min ETA=1.0min avg_latency=0.0004s/user
[Content-Based (cosine on embeddings)] 66000/221469 (29.8%) elapsed=0.4min ETA=1.0min avg_latency=0.0004s/user
[Content-Based (cosine on embeddings)] 68000/221469 (30.7%) elapsed=0.4min ETA=0.9min avg_latency=0.0004s/user
[Content-Based (cosine on embeddings)] 70000/221469 (31.6%) elapsed=0.4min ETA=0.9min avg_latency=0.0004s/user
[Content-Based (cosine on embeddings)] 72000/221469 (32.5%) elapsed=0.4min ETA=0.9min avg_latency=0.0003s/user
[Content-Based (cosine on embeddings)] 74000/221469 (33.4%) elapsed=0.4min ETA=0.8min avg_latency=0.0003s/user
[Content-Based (cosine on embeddings)] 76000/221469 (34.3%) elapsed=0.4min ETA=0.8min avg_latency=0.0003s/user
[Content-Based (cosine on embeddings)] 78000/221469 (35.2%) elapsed=0.4min ETA=0.8min avg_latency=0.0003s/user
[Content-Based (cosine on embeddings)] 80000/221469 (36.1%) elapsed=0.4min ETA=0.7min avg_latency=0.0003s/user
[Content-Based (cosine on embeddings)] 82000/221469 (37.0%) elapsed=0.4min ETA=0.7min avg_latency=0.0003s/user
[Content-Based (cosine on embeddings)] 84000/221469 (37.9%) elapsed=0.4min ETA=0.7min avg_latency=0.0003s/user
[Content-Based (cosine on embeddings)] 86000/221469 (38.8%) elapsed=0.4min ETA=0.7min avg_latency=0.0003s/user
[Content-Based (cosine on embeddings)] 88000/221469 (39.7%) elapsed=0.4min ETA=0.6min avg_latency=0.0003s/user
[Content-Based (cosine on embeddings)] 90000/221469 (40.6%) elapsed=0.4min ETA=0.6min avg_latency=0.0003s/user
[Content-Based (cosine on embeddings)] 92000/221469 (41.5%) elapsed=0.4min ETA=0.6min avg_latency=0.0003s/user
[Content-Based (cosine on embeddings)] 94000/221469 (42.4%) elapsed=0.4min ETA=0.6min avg_latency=0.0003s/user
[Content-Based (cosine on embeddings)] 96000/221469 (43.3%) elapsed=0.4min ETA=0.6min avg_latency=0.0003s/user
[Content-Based (cosine on embeddings)] 98000/221469 (44.2%) elapsed=0.4min ETA=0.5min avg_latency=0.0003s/user
[Content-Based (cosine on embeddings)] 100000/221469 (45.2%) elapsed=0.4min ETA=0.5min avg_latency=0.0003s/user
[Content-Based (cosine on embeddings)] 102000/221469 (46.1%) elapsed=0.4min ETA=0.5min avg_latency=0.0003s/user
[Content-Based (cosine on embeddings)] 104000/221469 (47.0%) elapsed=0.4min ETA=0.5min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 106000/221469 (47.9%) elapsed=0.4min ETA=0.5min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 108000/221469 (48.8%) elapsed=0.4min ETA=0.5min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 110000/221469 (49.7%) elapsed=0.4min ETA=0.4min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 112000/221469 (50.6%) elapsed=0.5min ETA=0.5min avg_latency=0.0003s/user
[Content-Based (cosine on embeddings)] 114000/221469 (51.5%) elapsed=0.5min ETA=0.5min avg_latency=0.0003s/user
[Content-Based (cosine on embeddings)] 116000/221469 (52.4%) elapsed=0.5min ETA=0.5min avg_latency=0.0003s/user
[Content-Based (cosine on embeddings)] 118000/221469 (53.3%) elapsed=0.5min ETA=0.5min avg_latency=0.0003s/user
[Content-Based (cosine on embeddings)] 120000/221469 (54.2%) elapsed=0.5min ETA=0.5min avg_latency=0.0003s/user
[Content-Based (cosine on embeddings)] 122000/221469 (55.1%) elapsed=0.5min ETA=0.4min avg_latency=0.0003s/user
[Content-Based (cosine on embeddings)] 124000/221469 (56.0%) elapsed=0.5min ETA=0.4min avg_latency=0.0003s/user
[Content-Based (cosine on embeddings)] 126000/221469 (56.9%) elapsed=0.5min ETA=0.4min avg_latency=0.0003s/user
[Content-Based (cosine on embeddings)] 128000/221469 (57.8%) elapsed=0.5min ETA=0.4min avg_latency=0.0003s/user
[Content-Based (cosine on embeddings)] 130000/221469 (58.7%) elapsed=0.5min ETA=0.4min avg_latency=0.0003s/user
[Content-Based (cosine on embeddings)] 132000/221469 (59.6%) elapsed=0.5min ETA=0.4min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 134000/221469 (60.5%) elapsed=0.5min ETA=0.4min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 136000/221469 (61.4%) elapsed=0.5min ETA=0.3min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 138000/221469 (62.3%) elapsed=0.5min ETA=0.3min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 140000/221469 (63.2%) elapsed=0.5min ETA=0.3min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 142000/221469 (64.1%) elapsed=0.6min ETA=0.3min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 144000/221469 (65.0%) elapsed=0.6min ETA=0.3min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 146000/221469 (65.9%) elapsed=0.6min ETA=0.3min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 148000/221469 (66.8%) elapsed=0.6min ETA=0.3min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 150000/221469 (67.7%) elapsed=0.6min ETA=0.3min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 152000/221469 (68.6%) elapsed=0.6min ETA=0.3min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 154000/221469 (69.5%) elapsed=0.6min ETA=0.2min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 156000/221469 (70.4%) elapsed=0.6min ETA=0.2min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 158000/221469 (71.3%) elapsed=0.6min ETA=0.2min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 160000/221469 (72.2%) elapsed=0.6min ETA=0.2min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 162000/221469 (73.1%) elapsed=0.6min ETA=0.2min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 164000/221469 (74.1%) elapsed=0.6min ETA=0.2min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 166000/221469 (75.0%) elapsed=0.6min ETA=0.2min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 168000/221469 (75.9%) elapsed=0.7min ETA=0.2min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 170000/221469 (76.8%) elapsed=0.7min ETA=0.2min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 172000/221469 (77.7%) elapsed=0.7min ETA=0.2min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 174000/221469 (78.6%) elapsed=0.7min ETA=0.2min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 176000/221469 (79.5%) elapsed=0.7min ETA=0.2min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 178000/221469 (80.4%) elapsed=0.7min ETA=0.2min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 180000/221469 (81.3%) elapsed=0.7min ETA=0.2min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 182000/221469 (82.2%) elapsed=0.7min ETA=0.1min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 184000/221469 (83.1%) elapsed=0.7min ETA=0.1min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 186000/221469 (84.0%) elapsed=0.7min ETA=0.1min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 188000/221469 (84.9%) elapsed=0.7min ETA=0.1min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 190000/221469 (85.8%) elapsed=0.7min ETA=0.1min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 192000/221469 (86.7%) elapsed=0.7min ETA=0.1min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 194000/221469 (87.6%) elapsed=0.7min ETA=0.1min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 196000/221469 (88.5%) elapsed=0.7min ETA=0.1min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 198000/221469 (89.4%) elapsed=0.7min ETA=0.1min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 200000/221469 (90.3%) elapsed=0.7min ETA=0.1min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 202000/221469 (91.2%) elapsed=0.7min ETA=0.1min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 204000/221469 (92.1%) elapsed=0.7min ETA=0.1min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 206000/221469 (93.0%) elapsed=0.7min ETA=0.1min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 208000/221469 (93.9%) elapsed=0.7min ETA=0.0min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 210000/221469 (94.8%) elapsed=0.7min ETA=0.0min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 212000/221469 (95.7%) elapsed=0.7min ETA=0.0min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 214000/221469 (96.6%) elapsed=0.7min ETA=0.0min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 216000/221469 (97.5%) elapsed=0.7min ETA=0.0min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 218000/221469 (98.4%) elapsed=0.7min ETA=0.0min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 220000/221469 (99.3%) elapsed=0.7min ETA=0.0min avg_latency=0.0002s/user
[Content-Based (cosine on embeddings)] 221469/221469 (100.0%) elapsed=0.7min ETA=0.0min avg_latency=0.0002s/user
✔ Done: Content-Based (cosine on embeddings) in 0.7min | mean_latency=0.0012s/user | coverage=0.0066

In [15]:
results.append(
    evaluate_model(
        "SVD++ basic",
        lambda user_id, k: recommend_surprise(svdpp_model, user_id, k),
        test_df,
        CONFIG["k"],
        predict_fn=make_predict_fn(svdpp_model),
        rmse_df=test_ratings_df,
    )
)

▶ Evaluating: SVD++ basic | users=221469 | k=5
[SVD++ basic] 1/221469 (0.0%) elapsed=11.2min ETA=2486309.1min avg_latency=673.5896s/user
[SVD++ basic] 2000/221469 (0.9%) elapsed=11.2min ETA=1231.9min avg_latency=0.3368s/user
[SVD++ basic] 4000/221469 (1.8%) elapsed=11.2min ETA=610.4min avg_latency=0.1684s/user
[SVD++ basic] 6000/221469 (2.7%) elapsed=11.2min ETA=403.2min avg_latency=0.1123s/user
[SVD++ basic] 8000/221469 (3.6%) elapsed=11.5min ETA=305.6min avg_latency=0.0859s/user
[SVD++ basic] 10000/221469 (4.5%) elapsed=11.5min ETA=242.2min avg_latency=0.0687s/user
[SVD++ basic] 12000/221469 (5.4%) elapsed=11.5min ETA=199.9min avg_latency=0.0573s/user
[SVD++ basic] 14000/221469 (6.3%) elapsed=12.5min ETA=185.8min avg_latency=0.0537s/user
[SVD++ basic] 16000/221469 (7.2%) elapsed=12.5min ETA=161.0min avg_latency=0.0470s/user
[SVD++ basic] 18000/221469 (8.1%) elapsed=12.5min ETA=141.7min avg_latency=0.0418s/user
[SVD++ basic] 20000/221469 (9.0%) elapsed=12.9min ETA=129.7min avg_latency=0.0386s/user
[SVD++ basic] 22000/221469 (9.9%) elapsed=12.9min ETA=116.7min avg_latency=0.0351s/user
[SVD++ basic] 24000/221469 (10.8%) elapsed=12.9min ETA=105.9min avg_latency=0.0322s/user
[SVD++ basic] 26000/221469 (11.7%) elapsed=13.2min ETA=99.5min avg_latency=0.0305s/user
[SVD++ basic] 28000/221469 (12.6%) elapsed=13.2min ETA=91.4min avg_latency=0.0284s/user
[SVD++ basic] 30000/221469 (13.5%) elapsed=13.2min ETA=84.4min avg_latency=0.0265s/user
[SVD++ basic] 32000/221469 (14.4%) elapsed=13.6min ETA=80.3min avg_latency=0.0254s/user
[SVD++ basic] 34000/221469 (15.4%) elapsed=13.6min ETA=74.8min avg_latency=0.0239s/user
[SVD++ basic] 36000/221469 (16.3%) elapsed=13.6min ETA=69.9min avg_latency=0.0226s/user
[SVD++ basic] 38000/221469 (17.2%) elapsed=14.0min ETA=67.6min avg_latency=0.0221s/user
[SVD++ basic] 40000/221469 (18.1%) elapsed=14.0min ETA=63.5min avg_latency=0.0210s/user
[SVD++ basic] 42000/221469 (19.0%) elapsed=14.0min ETA=59.8min avg_latency=0.0200s/user
[SVD++ basic] 44000/221469 (19.9%) elapsed=14.2min ETA=57.3min avg_latency=0.0194s/user
[SVD++ basic] 46000/221469 (20.8%) elapsed=14.2min ETA=54.2min avg_latency=0.0185s/user
[SVD++ basic] 48000/221469 (21.7%) elapsed=14.2min ETA=51.3min avg_latency=0.0178s/user
[SVD++ basic] 50000/221469 (22.6%) elapsed=14.9min ETA=51.3min avg_latency=0.0179s/user
[SVD++ basic] 52000/221469 (23.5%) elapsed=14.9min ETA=48.7min avg_latency=0.0172s/user
[SVD++ basic] 54000/221469 (24.4%) elapsed=14.9min ETA=46.4min avg_latency=0.0166s/user
[SVD++ basic] 56000/221469 (25.3%) elapsed=22.5min ETA=66.4min avg_latency=0.0241s/user
[SVD++ basic] 58000/221469 (26.2%) elapsed=22.5min ETA=63.3min avg_latency=0.0232s/user
[SVD++ basic] 60000/221469 (27.1%) elapsed=22.5min ETA=60.4min avg_latency=0.0225s/user
[SVD++ basic] 62000/221469 (28.0%) elapsed=22.6min ETA=58.1min avg_latency=0.0219s/user
[SVD++ basic] 64000/221469 (28.9%) elapsed=22.6min ETA=55.6min avg_latency=0.0212s/user
[SVD++ basic] 66000/221469 (29.8%) elapsed=22.6min ETA=53.2min avg_latency=0.0205s/user
[SVD++ basic] 68000/221469 (30.7%) elapsed=22.8min ETA=51.5min avg_latency=0.0201s/user
[SVD++ basic] 70000/221469 (31.6%) elapsed=22.8min ETA=49.4min avg_latency=0.0196s/user
[SVD++ basic] 72000/221469 (32.5%) elapsed=22.8min ETA=47.4min avg_latency=0.0190s/user
[SVD++ basic] 74000/221469 (33.4%) elapsed=22.8min ETA=45.5min avg_latency=0.0185s/user
[SVD++ basic] 76000/221469 (34.3%) elapsed=22.8min ETA=43.7min avg_latency=0.0180s/user
[SVD++ basic] 78000/221469 (35.2%) elapsed=22.8min ETA=42.0min avg_latency=0.0176s/user
[SVD++ basic] 80000/221469 (36.1%) elapsed=23.1min ETA=40.9min avg_latency=0.0173s/user
[SVD++ basic] 82000/221469 (37.0%) elapsed=23.1min ETA=39.3min avg_latency=0.0169s/user
[SVD++ basic] 84000/221469 (37.9%) elapsed=23.1min ETA=37.8min avg_latency=0.0165s/user
[SVD++ basic] 86000/221469 (38.8%) elapsed=23.1min ETA=36.4min avg_latency=0.0161s/user
[SVD++ basic] 88000/221469 (39.7%) elapsed=23.2min ETA=35.2min avg_latency=0.0158s/user
[SVD++ basic] 90000/221469 (40.6%) elapsed=23.2min ETA=33.9min avg_latency=0.0155s/user
[SVD++ basic] 92000/221469 (41.5%) elapsed=23.2min ETA=32.6min avg_latency=0.0151s/user
[SVD++ basic] 94000/221469 (42.4%) elapsed=23.6min ETA=32.0min avg_latency=0.0150s/user
[SVD++ basic] 96000/221469 (43.3%) elapsed=23.6min ETA=30.8min avg_latency=0.0147s/user
[SVD++ basic] 98000/221469 (44.2%) elapsed=23.6min ETA=29.7min avg_latency=0.0144s/user
[SVD++ basic] 100000/221469 (45.2%) elapsed=23.7min ETA=28.8min avg_latency=0.0142s/user
[SVD++ basic] 102000/221469 (46.1%) elapsed=23.7min ETA=27.8min avg_latency=0.0139s/user
[SVD++ basic] 104000/221469 (47.0%) elapsed=23.7min ETA=26.8min avg_latency=0.0137s/user
[SVD++ basic] 106000/221469 (47.9%) elapsed=24.5min ETA=26.7min avg_latency=0.0139s/user
[SVD++ basic] 108000/221469 (48.8%) elapsed=24.5min ETA=25.7min avg_latency=0.0136s/user
[SVD++ basic] 110000/221469 (49.7%) elapsed=24.5min ETA=24.8min avg_latency=0.0134s/user
[SVD++ basic] 112000/221469 (50.6%) elapsed=31.1min ETA=30.4min avg_latency=0.0167s/user
[SVD++ basic] 114000/221469 (51.5%) elapsed=31.1min ETA=29.3min avg_latency=0.0164s/user
[SVD++ basic] 116000/221469 (52.4%) elapsed=31.1min ETA=28.3min avg_latency=0.0161s/user
[SVD++ basic] 118000/221469 (53.3%) elapsed=31.2min ETA=27.4min avg_latency=0.0159s/user
[SVD++ basic] 120000/221469 (54.2%) elapsed=31.2min ETA=26.4min avg_latency=0.0156s/user
[SVD++ basic] 122000/221469 (55.1%) elapsed=31.2min ETA=25.5min avg_latency=0.0154s/user
[SVD++ basic] 124000/221469 (56.0%) elapsed=31.3min ETA=24.6min avg_latency=0.0152s/user
[SVD++ basic] 126000/221469 (56.9%) elapsed=31.3min ETA=23.7min avg_latency=0.0149s/user
[SVD++ basic] 128000/221469 (57.8%) elapsed=31.3min ETA=22.9min avg_latency=0.0147s/user
[SVD++ basic] 130000/221469 (58.7%) elapsed=31.4min ETA=22.1min avg_latency=0.0145s/user
[SVD++ basic] 132000/221469 (59.6%) elapsed=31.4min ETA=21.3min avg_latency=0.0143s/user
[SVD++ basic] 134000/221469 (60.5%) elapsed=31.4min ETA=20.5min avg_latency=0.0140s/user
[SVD++ basic] 136000/221469 (61.4%) elapsed=31.4min ETA=19.7min avg_latency=0.0139s/user
[SVD++ basic] 138000/221469 (62.3%) elapsed=31.4min ETA=19.0min avg_latency=0.0137s/user
[SVD++ basic] 140000/221469 (63.2%) elapsed=31.4min ETA=18.3min avg_latency=0.0135s/user
[SVD++ basic] 142000/221469 (64.1%) elapsed=31.4min ETA=17.6min avg_latency=0.0133s/user
[SVD++ basic] 144000/221469 (65.0%) elapsed=31.4min ETA=16.9min avg_latency=0.0131s/user
[SVD++ basic] 146000/221469 (65.9%) elapsed=31.4min ETA=16.2min avg_latency=0.0129s/user
[SVD++ basic] 148000/221469 (66.8%) elapsed=31.4min ETA=15.6min avg_latency=0.0127s/user
[SVD++ basic] 150000/221469 (67.7%) elapsed=31.4min ETA=15.0min avg_latency=0.0126s/user
[SVD++ basic] 152000/221469 (68.6%) elapsed=31.4min ETA=14.4min avg_latency=0.0124s/user
[SVD++ basic] 154000/221469 (69.5%) elapsed=31.5min ETA=13.8min avg_latency=0.0123s/user
[SVD++ basic] 156000/221469 (70.4%) elapsed=31.5min ETA=13.2min avg_latency=0.0121s/user
[SVD++ basic] 158000/221469 (71.3%) elapsed=31.5min ETA=12.6min avg_latency=0.0119s/user
[SVD++ basic] 160000/221469 (72.2%) elapsed=32.1min ETA=12.3min avg_latency=0.0120s/user
[SVD++ basic] 162000/221469 (73.1%) elapsed=32.1min ETA=11.8min avg_latency=0.0119s/user
[SVD++ basic] 164000/221469 (74.1%) elapsed=32.1min ETA=11.2min avg_latency=0.0117s/user
[SVD++ basic] 166000/221469 (75.0%) elapsed=32.1min ETA=10.7min avg_latency=0.0116s/user
[SVD++ basic] 168000/221469 (75.9%) elapsed=37.8min ETA=12.0min avg_latency=0.0135s/user
[SVD++ basic] 170000/221469 (76.8%) elapsed=37.8min ETA=11.5min avg_latency=0.0133s/user
[SVD++ basic] 172000/221469 (77.7%) elapsed=37.8min ETA=10.9min avg_latency=0.0132s/user
[SVD++ basic] 174000/221469 (78.6%) elapsed=37.9min ETA=10.3min avg_latency=0.0131s/user
[SVD++ basic] 176000/221469 (79.5%) elapsed=37.9min ETA=9.8min avg_latency=0.0129s/user
[SVD++ basic] 178000/221469 (80.4%) elapsed=37.9min ETA=9.2min avg_latency=0.0128s/user
[SVD++ basic] 180000/221469 (81.3%) elapsed=38.1min ETA=8.8min avg_latency=0.0127s/user
[SVD++ basic] 182000/221469 (82.2%) elapsed=38.1min ETA=8.3min avg_latency=0.0125s/user
[SVD++ basic] 184000/221469 (83.1%) elapsed=38.1min ETA=7.8min avg_latency=0.0124s/user
[SVD++ basic] 186000/221469 (84.0%) elapsed=38.1min ETA=7.3min avg_latency=0.0123s/user
[SVD++ basic] 188000/221469 (84.9%) elapsed=38.1min ETA=6.8min avg_latency=0.0122s/user
[SVD++ basic] 190000/221469 (85.8%) elapsed=38.1min ETA=6.3min avg_latency=0.0120s/user
[SVD++ basic] 192000/221469 (86.7%) elapsed=38.2min ETA=5.9min avg_latency=0.0119s/user
[SVD++ basic] 194000/221469 (87.6%) elapsed=38.2min ETA=5.4min avg_latency=0.0118s/user
[SVD++ basic] 196000/221469 (88.5%) elapsed=38.2min ETA=5.0min avg_latency=0.0117s/user
[SVD++ basic] 198000/221469 (89.4%) elapsed=38.3min ETA=4.5min avg_latency=0.0116s/user
[SVD++ basic] 200000/221469 (90.3%) elapsed=38.3min ETA=4.1min avg_latency=0.0115s/user
[SVD++ basic] 202000/221469 (91.2%) elapsed=38.3min ETA=3.7min avg_latency=0.0114s/user
[SVD++ basic] 204000/221469 (92.1%) elapsed=38.3min ETA=3.3min avg_latency=0.0113s/user
[SVD++ basic] 206000/221469 (93.0%) elapsed=38.3min ETA=2.9min avg_latency=0.0112s/user
[SVD++ basic] 208000/221469 (93.9%) elapsed=38.3min ETA=2.5min avg_latency=0.0111s/user
[SVD++ basic] 210000/221469 (94.8%) elapsed=38.4min ETA=2.1min avg_latency=0.0110s/user
[SVD++ basic] 212000/221469 (95.7%) elapsed=38.4min ETA=1.7min avg_latency=0.0109s/user
[SVD++ basic] 214000/221469 (96.6%) elapsed=38.4min ETA=1.3min avg_latency=0.0108s/user
[SVD++ basic] 216000/221469 (97.5%) elapsed=38.4min ETA=1.0min avg_latency=0.0107s/user
[SVD++ basic] 218000/221469 (98.4%) elapsed=38.4min ETA=0.6min avg_latency=0.0106s/user
[SVD++ basic] 220000/221469 (99.3%) elapsed=38.4min ETA=0.3min avg_latency=0.0105s/user
[SVD++ basic] 221469/221469 (100.0%) elapsed=38.4min ETA=0.0min avg_latency=0.0104s/user
✔ Done: SVD++ basic in 38.4min | mean_latency=0.0926s/user | coverage=0.3732

In [16]:
results.append(
    evaluate_model(
        "SVD++ + session weighting",
        lambda user_id, k: recommend_surprise(svdpp_weighted_model, user_id, k),
        test_df,
        CONFIG["k"],
        predict_fn=make_predict_fn(svdpp_weighted_model),
        rmse_df=test_ratings_df,
    )
)

▶ Evaluating: SVD++ + session weighting | users=221469 | k=5
[SVD++ + session weighting] 1/221469 (0.0%) elapsed=11.6min ETA=2568048.0min avg_latency=695.7343s/user
[SVD++ + session weighting] 2000/221469 (0.9%) elapsed=11.6min ETA=1272.4min avg_latency=0.3479s/user
[SVD++ + session weighting] 4000/221469 (1.8%) elapsed=11.6min ETA=630.4min avg_latency=0.1739s/user
[SVD++ + session weighting] 6000/221469 (2.7%) elapsed=11.6min ETA=416.4min avg_latency=0.1160s/user
[SVD++ + session weighting] 8000/221469 (3.6%) elapsed=11.9min ETA=317.6min avg_latency=0.0893s/user
[SVD++ + session weighting] 10000/221469 (4.5%) elapsed=11.9min ETA=251.7min avg_latency=0.0714s/user
[SVD++ + session weighting] 12000/221469 (5.4%) elapsed=11.9min ETA=207.7min avg_latency=0.0595s/user
[SVD++ + session weighting] 14000/221469 (6.3%) elapsed=13.0min ETA=193.3min avg_latency=0.0559s/user
[SVD++ + session weighting] 16000/221469 (7.2%) elapsed=13.0min ETA=167.5min avg_latency=0.0489s/user
[SVD++ + session weighting] 18000/221469 (8.1%) elapsed=13.0min ETA=147.4min avg_latency=0.0435s/user
[SVD++ + session weighting] 20000/221469 (9.0%) elapsed=13.3min ETA=134.2min avg_latency=0.0400s/user
[SVD++ + session weighting] 22000/221469 (9.9%) elapsed=13.3min ETA=120.8min avg_latency=0.0363s/user
[SVD++ + session weighting] 24000/221469 (10.8%) elapsed=13.3min ETA=109.6min avg_latency=0.0333s/user
[SVD++ + session weighting] 26000/221469 (11.7%) elapsed=13.6min ETA=102.3min avg_latency=0.0314s/user
[SVD++ + session weighting] 28000/221469 (12.6%) elapsed=13.6min ETA=94.0min avg_latency=0.0291s/user
[SVD++ + session weighting] 30000/221469 (13.5%) elapsed=13.6min ETA=86.8min avg_latency=0.0272s/user
[SVD++ + session weighting] 32000/221469 (14.4%) elapsed=14.1min ETA=83.3min avg_latency=0.0264s/user
[SVD++ + session weighting] 34000/221469 (15.4%) elapsed=14.1min ETA=77.5min avg_latency=0.0248s/user
[SVD++ + session weighting] 36000/221469 (16.3%) elapsed=14.1min ETA=72.4min avg_latency=0.0234s/user
[SVD++ + session weighting] 38000/221469 (17.2%) elapsed=14.4min ETA=69.5min avg_latency=0.0227s/user
[SVD++ + session weighting] 40000/221469 (18.1%) elapsed=14.4min ETA=65.3min avg_latency=0.0216s/user
[SVD++ + session weighting] 42000/221469 (19.0%) elapsed=14.4min ETA=61.5min avg_latency=0.0206s/user
[SVD++ + session weighting] 44000/221469 (19.9%) elapsed=14.8min ETA=59.7min avg_latency=0.0202s/user
[SVD++ + session weighting] 46000/221469 (20.8%) elapsed=14.8min ETA=56.5min avg_latency=0.0193s/user
[SVD++ + session weighting] 48000/221469 (21.7%) elapsed=14.8min ETA=53.5min avg_latency=0.0185s/user
[SVD++ + session weighting] 50000/221469 (22.6%) elapsed=15.5min ETA=53.1min avg_latency=0.0186s/user
[SVD++ + session weighting] 52000/221469 (23.5%) elapsed=15.5min ETA=50.5min avg_latency=0.0179s/user
[SVD++ + session weighting] 54000/221469 (24.4%) elapsed=15.5min ETA=48.0min avg_latency=0.0172s/user
[SVD++ + session weighting] 56000/221469 (25.3%) elapsed=23.3min ETA=69.0min avg_latency=0.0250s/user
[SVD++ + session weighting] 58000/221469 (26.2%) elapsed=23.3min ETA=65.8min avg_latency=0.0241s/user
[SVD++ + session weighting] 60000/221469 (27.1%) elapsed=23.3min ETA=62.8min avg_latency=0.0233s/user
[SVD++ + session weighting] 62000/221469 (28.0%) elapsed=23.6min ETA=60.7min avg_latency=0.0228s/user
[SVD++ + session weighting] 64000/221469 (28.9%) elapsed=23.6min ETA=58.0min avg_latency=0.0221s/user
[SVD++ + session weighting] 66000/221469 (29.8%) elapsed=23.6min ETA=55.6min avg_latency=0.0214s/user
[SVD++ + session weighting] 68000/221469 (30.7%) elapsed=23.6min ETA=53.3min avg_latency=0.0208s/user
[SVD++ + session weighting] 70000/221469 (31.6%) elapsed=23.6min ETA=51.1min avg_latency=0.0203s/user
[SVD++ + session weighting] 72000/221469 (32.5%) elapsed=23.6min ETA=49.0min avg_latency=0.0197s/user
[SVD++ + session weighting] 74000/221469 (33.4%) elapsed=23.7min ETA=47.2min avg_latency=0.0192s/user
[SVD++ + session weighting] 76000/221469 (34.3%) elapsed=23.7min ETA=45.3min avg_latency=0.0187s/user
[SVD++ + session weighting] 78000/221469 (35.2%) elapsed=23.7min ETA=43.5min avg_latency=0.0182s/user
[SVD++ + session weighting] 80000/221469 (36.1%) elapsed=23.8min ETA=42.0min avg_latency=0.0178s/user
[SVD++ + session weighting] 82000/221469 (37.0%) elapsed=23.8min ETA=40.4min avg_latency=0.0174s/user
[SVD++ + session weighting] 84000/221469 (37.9%) elapsed=23.8min ETA=38.9min avg_latency=0.0170s/user
[SVD++ + session weighting] 86000/221469 (38.8%) elapsed=23.8min ETA=37.5min avg_latency=0.0166s/user
[SVD++ + session weighting] 88000/221469 (39.7%) elapsed=24.1min ETA=36.5min avg_latency=0.0164s/user
[SVD++ + session weighting] 90000/221469 (40.6%) elapsed=24.1min ETA=35.2min avg_latency=0.0161s/user
[SVD++ + session weighting] 92000/221469 (41.5%) elapsed=24.1min ETA=33.9min avg_latency=0.0157s/user
[SVD++ + session weighting] 94000/221469 (42.4%) elapsed=24.7min ETA=33.4min avg_latency=0.0157s/user
[SVD++ + session weighting] 96000/221469 (43.3%) elapsed=24.7min ETA=32.2min avg_latency=0.0154s/user
[SVD++ + session weighting] 98000/221469 (44.2%) elapsed=24.7min ETA=31.1min avg_latency=0.0151s/user
[SVD++ + session weighting] 100000/221469 (45.2%) elapsed=24.9min ETA=30.2min avg_latency=0.0149s/user
[SVD++ + session weighting] 102000/221469 (46.1%) elapsed=24.9min ETA=29.1min avg_latency=0.0146s/user
[SVD++ + session weighting] 104000/221469 (47.0%) elapsed=24.9min ETA=28.1min avg_latency=0.0143s/user
[SVD++ + session weighting] 106000/221469 (47.9%) elapsed=25.5min ETA=27.8min avg_latency=0.0144s/user
[SVD++ + session weighting] 108000/221469 (48.8%) elapsed=25.5min ETA=26.8min avg_latency=0.0142s/user
[SVD++ + session weighting] 110000/221469 (49.7%) elapsed=25.5min ETA=25.8min avg_latency=0.0139s/user
[SVD++ + session weighting] 112000/221469 (50.6%) elapsed=32.2min ETA=31.5min avg_latency=0.0173s/user
[SVD++ + session weighting] 114000/221469 (51.5%) elapsed=32.2min ETA=30.4min avg_latency=0.0170s/user
[SVD++ + session weighting] 116000/221469 (52.4%) elapsed=32.2min ETA=29.3min avg_latency=0.0167s/user
[SVD++ + session weighting] 118000/221469 (53.3%) elapsed=32.3min ETA=28.3min avg_latency=0.0164s/user
[SVD++ + session weighting] 120000/221469 (54.2%) elapsed=32.3min ETA=27.3min avg_latency=0.0162s/user
[SVD++ + session weighting] 122000/221469 (55.1%) elapsed=32.3min ETA=26.4min avg_latency=0.0159s/user
[SVD++ + session weighting] 124000/221469 (56.0%) elapsed=32.6min ETA=25.6min avg_latency=0.0158s/user
[SVD++ + session weighting] 126000/221469 (56.9%) elapsed=32.6min ETA=24.7min avg_latency=0.0155s/user
[SVD++ + session weighting] 128000/221469 (57.8%) elapsed=32.6min ETA=23.8min avg_latency=0.0153s/user
[SVD++ + session weighting] 130000/221469 (58.7%) elapsed=32.6min ETA=22.9min avg_latency=0.0150s/user
[SVD++ + session weighting] 132000/221469 (59.6%) elapsed=32.6min ETA=22.1min avg_latency=0.0148s/user
[SVD++ + session weighting] 134000/221469 (60.5%) elapsed=32.6min ETA=21.3min avg_latency=0.0146s/user
[SVD++ + session weighting] 136000/221469 (61.4%) elapsed=32.8min ETA=20.6min avg_latency=0.0144s/user
[SVD++ + session weighting] 138000/221469 (62.3%) elapsed=32.8min ETA=19.8min avg_latency=0.0142s/user
[SVD++ + session weighting] 140000/221469 (63.2%) elapsed=32.8min ETA=19.1min avg_latency=0.0140s/user
[SVD++ + session weighting] 142000/221469 (64.1%) elapsed=32.8min ETA=18.3min avg_latency=0.0138s/user
[SVD++ + session weighting] 144000/221469 (65.0%) elapsed=32.8min ETA=17.6min avg_latency=0.0136s/user
[SVD++ + session weighting] 146000/221469 (65.9%) elapsed=32.8min ETA=16.9min avg_latency=0.0135s/user
[SVD++ + session weighting] 148000/221469 (66.8%) elapsed=32.8min ETA=16.3min avg_latency=0.0133s/user
[SVD++ + session weighting] 150000/221469 (67.7%) elapsed=32.8min ETA=15.6min avg_latency=0.0131s/user
[SVD++ + session weighting] 152000/221469 (68.6%) elapsed=32.8min ETA=15.0min avg_latency=0.0129s/user
[SVD++ + session weighting] 154000/221469 (69.5%) elapsed=33.0min ETA=14.5min avg_latency=0.0129s/user
[SVD++ + session weighting] 156000/221469 (70.4%) elapsed=33.0min ETA=13.8min avg_latency=0.0127s/user
[SVD++ + session weighting] 158000/221469 (71.3%) elapsed=33.0min ETA=13.3min avg_latency=0.0125s/user
[SVD++ + session weighting] 160000/221469 (72.2%) elapsed=33.5min ETA=12.9min avg_latency=0.0125s/user
[SVD++ + session weighting] 162000/221469 (73.1%) elapsed=33.5min ETA=12.3min avg_latency=0.0124s/user
[SVD++ + session weighting] 164000/221469 (74.1%) elapsed=33.5min ETA=11.7min avg_latency=0.0122s/user
[SVD++ + session weighting] 166000/221469 (75.0%) elapsed=33.5min ETA=11.2min avg_latency=0.0121s/user
[SVD++ + session weighting] 168000/221469 (75.9%) elapsed=39.6min ETA=12.6min avg_latency=0.0141s/user
[SVD++ + session weighting] 170000/221469 (76.8%) elapsed=39.6min ETA=12.0min avg_latency=0.0140s/user
[SVD++ + session weighting] 172000/221469 (77.7%) elapsed=39.6min ETA=11.4min avg_latency=0.0138s/user
[SVD++ + session weighting] 174000/221469 (78.6%) elapsed=39.6min ETA=10.8min avg_latency=0.0137s/user
[SVD++ + session weighting] 176000/221469 (79.5%) elapsed=39.6min ETA=10.2min avg_latency=0.0135s/user
[SVD++ + session weighting] 178000/221469 (80.4%) elapsed=39.6min ETA=9.7min avg_latency=0.0134s/user
[SVD++ + session weighting] 180000/221469 (81.3%) elapsed=39.6min ETA=9.1min avg_latency=0.0132s/user
[SVD++ + session weighting] 182000/221469 (82.2%) elapsed=39.6min ETA=8.6min avg_latency=0.0131s/user
[SVD++ + session weighting] 184000/221469 (83.1%) elapsed=39.6min ETA=8.1min avg_latency=0.0129s/user
[SVD++ + session weighting] 186000/221469 (84.0%) elapsed=39.6min ETA=7.6min avg_latency=0.0128s/user
[SVD++ + session weighting] 188000/221469 (84.9%) elapsed=39.6min ETA=7.1min avg_latency=0.0127s/user
[SVD++ + session weighting] 190000/221469 (85.8%) elapsed=39.6min ETA=6.6min avg_latency=0.0125s/user
[SVD++ + session weighting] 192000/221469 (86.7%) elapsed=39.8min ETA=6.1min avg_latency=0.0124s/user
[SVD++ + session weighting] 194000/221469 (87.6%) elapsed=39.8min ETA=5.6min avg_latency=0.0123s/user
[SVD++ + session weighting] 196000/221469 (88.5%) elapsed=39.8min ETA=5.2min avg_latency=0.0122s/user
[SVD++ + session weighting] 198000/221469 (89.4%) elapsed=39.8min ETA=4.7min avg_latency=0.0121s/user
[SVD++ + session weighting] 200000/221469 (90.3%) elapsed=39.8min ETA=4.3min avg_latency=0.0119s/user
[SVD++ + session weighting] 202000/221469 (91.2%) elapsed=39.8min ETA=3.8min avg_latency=0.0118s/user
[SVD++ + session weighting] 204000/221469 (92.1%) elapsed=39.8min ETA=3.4min avg_latency=0.0117s/user
[SVD++ + session weighting] 206000/221469 (93.0%) elapsed=39.8min ETA=3.0min avg_latency=0.0116s/user
[SVD++ + session weighting] 208000/221469 (93.9%) elapsed=39.8min ETA=2.6min avg_latency=0.0115s/user
[SVD++ + session weighting] 210000/221469 (94.8%) elapsed=39.9min ETA=2.2min avg_latency=0.0114s/user
[SVD++ + session weighting] 212000/221469 (95.7%) elapsed=39.9min ETA=1.8min avg_latency=0.0113s/user
[SVD++ + session weighting] 214000/221469 (96.6%) elapsed=39.9min ETA=1.4min avg_latency=0.0112s/user
[SVD++ + session weighting] 216000/221469 (97.5%) elapsed=39.9min ETA=1.0min avg_latency=0.0111s/user
[SVD++ + session weighting] 218000/221469 (98.4%) elapsed=39.9min ETA=0.6min avg_latency=0.0110s/user
[SVD++ + session weighting] 220000/221469 (99.3%) elapsed=39.9min ETA=0.3min avg_latency=0.0109s/user
[SVD++ + session weighting] 221469/221469 (100.0%) elapsed=39.9min ETA=0.0min avg_latency=0.0108s/user
✔ Done: SVD++ + session weighting in 39.9min | mean_latency=0.0964s/user | coverage=0.4474

In [17]:
results.append(
    evaluate_model(
        "Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)",
        lambda user_id, k: recommend_hybrid_rank_fusion(user_id, k, weight_cf=hybrid_weight_cf, weight_cb=hybrid_weight_cb),
        test_df,
        CONFIG["k"],
    )
)

▶ Evaluating: Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings) | users=221469 | k=5
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 1/221469 (0.0%) elapsed=12.0min ETA=2652071.2min avg_latency=718.4978s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 2000/221469 (0.9%) elapsed=12.0min ETA=1314.1min avg_latency=0.3593s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 4000/221469 (1.8%) elapsed=12.0min ETA=651.1min avg_latency=0.1796s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 6000/221469 (2.7%) elapsed=12.0min ETA=430.0min avg_latency=0.1198s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 8000/221469 (3.6%) elapsed=12.3min ETA=329.4min avg_latency=0.0926s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 10000/221469 (4.5%) elapsed=12.3min ETA=261.0min avg_latency=0.0741s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 12000/221469 (5.4%) elapsed=12.3min ETA=215.5min avg_latency=0.0617s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 14000/221469 (6.3%) elapsed=13.4min ETA=199.2min avg_latency=0.0576s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 16000/221469 (7.2%) elapsed=13.4min ETA=172.6min avg_latency=0.0504s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 18000/221469 (8.1%) elapsed=13.4min ETA=151.9min avg_latency=0.0448s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 20000/221469 (9.0%) elapsed=13.8min ETA=138.8min avg_latency=0.0413s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 22000/221469 (9.9%) elapsed=13.8min ETA=125.0min avg_latency=0.0376s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 24000/221469 (10.8%) elapsed=13.8min ETA=113.4min avg_latency=0.0345s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 26000/221469 (11.7%) elapsed=14.1min ETA=105.6min avg_latency=0.0324s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 28000/221469 (12.6%) elapsed=14.1min ETA=97.1min avg_latency=0.0301s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 30000/221469 (13.5%) elapsed=14.1min ETA=89.7min avg_latency=0.0281s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 32000/221469 (14.4%) elapsed=14.3min ETA=84.8min avg_latency=0.0269s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 34000/221469 (15.4%) elapsed=14.3min ETA=79.0min avg_latency=0.0253s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 36000/221469 (16.3%) elapsed=14.3min ETA=73.8min avg_latency=0.0239s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 38000/221469 (17.2%) elapsed=14.8min ETA=71.3min avg_latency=0.0233s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 40000/221469 (18.1%) elapsed=14.8min ETA=67.0min avg_latency=0.0222s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 42000/221469 (19.0%) elapsed=14.8min ETA=63.1min avg_latency=0.0211s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 44000/221469 (19.9%) elapsed=15.0min ETA=60.6min avg_latency=0.0205s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 46000/221469 (20.8%) elapsed=15.0min ETA=57.3min avg_latency=0.0196s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 48000/221469 (21.7%) elapsed=15.0min ETA=54.3min avg_latency=0.0188s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 50000/221469 (22.6%) elapsed=16.0min ETA=54.7min avg_latency=0.0192s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 52000/221469 (23.5%) elapsed=16.0min ETA=52.0min avg_latency=0.0184s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 54000/221469 (24.4%) elapsed=16.0min ETA=49.5min avg_latency=0.0177s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 56000/221469 (25.3%) elapsed=24.1min ETA=71.1min avg_latency=0.0258s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 58000/221469 (26.2%) elapsed=24.1min ETA=67.8min avg_latency=0.0249s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 60000/221469 (27.1%) elapsed=24.1min ETA=64.8min avg_latency=0.0241s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 62000/221469 (28.0%) elapsed=24.3min ETA=62.6min avg_latency=0.0235s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 64000/221469 (28.9%) elapsed=24.3min ETA=59.9min avg_latency=0.0228s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 66000/221469 (29.8%) elapsed=24.3min ETA=57.3min avg_latency=0.0221s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 68000/221469 (30.7%) elapsed=24.5min ETA=55.4min avg_latency=0.0217s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 70000/221469 (31.6%) elapsed=24.5min ETA=53.1min avg_latency=0.0210s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 72000/221469 (32.5%) elapsed=24.5min ETA=50.9min avg_latency=0.0204s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 74000/221469 (33.4%) elapsed=24.6min ETA=48.9min avg_latency=0.0199s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 76000/221469 (34.3%) elapsed=24.6min ETA=47.0min avg_latency=0.0194s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 78000/221469 (35.2%) elapsed=24.6min ETA=45.2min avg_latency=0.0189s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 80000/221469 (36.1%) elapsed=24.6min ETA=43.5min avg_latency=0.0185s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 82000/221469 (37.0%) elapsed=24.6min ETA=41.9min avg_latency=0.0180s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 84000/221469 (37.9%) elapsed=24.6min ETA=40.3min avg_latency=0.0176s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 86000/221469 (38.8%) elapsed=24.6min ETA=38.8min avg_latency=0.0172s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 88000/221469 (39.7%) elapsed=25.0min ETA=38.0min avg_latency=0.0171s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 90000/221469 (40.6%) elapsed=25.0min ETA=36.6min avg_latency=0.0167s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 92000/221469 (41.5%) elapsed=25.0min ETA=35.2min avg_latency=0.0163s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 94000/221469 (42.4%) elapsed=25.4min ETA=34.5min avg_latency=0.0162s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 96000/221469 (43.3%) elapsed=25.4min ETA=33.2min avg_latency=0.0159s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 98000/221469 (44.2%) elapsed=25.4min ETA=32.0min avg_latency=0.0156s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 100000/221469 (45.2%) elapsed=25.4min ETA=30.9min avg_latency=0.0153s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 102000/221469 (46.1%) elapsed=25.4min ETA=29.8min avg_latency=0.0150s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 104000/221469 (47.0%) elapsed=25.4min ETA=28.7min avg_latency=0.0147s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 106000/221469 (47.9%) elapsed=26.4min ETA=28.8min avg_latency=0.0150s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 108000/221469 (48.8%) elapsed=26.4min ETA=27.8min avg_latency=0.0147s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 110000/221469 (49.7%) elapsed=26.4min ETA=26.8min avg_latency=0.0144s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 112000/221469 (50.6%) elapsed=33.6min ETA=32.8min avg_latency=0.0180s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 114000/221469 (51.5%) elapsed=33.6min ETA=31.7min avg_latency=0.0177s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 116000/221469 (52.4%) elapsed=33.6min ETA=30.5min avg_latency=0.0174s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 118000/221469 (53.3%) elapsed=33.8min ETA=29.7min avg_latency=0.0172s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 120000/221469 (54.2%) elapsed=33.8min ETA=28.6min avg_latency=0.0169s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 122000/221469 (55.1%) elapsed=33.8min ETA=27.6min avg_latency=0.0166s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 124000/221469 (56.0%) elapsed=33.9min ETA=26.6min avg_latency=0.0164s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 126000/221469 (56.9%) elapsed=33.9min ETA=25.7min avg_latency=0.0161s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 128000/221469 (57.8%) elapsed=33.9min ETA=24.7min avg_latency=0.0159s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 130000/221469 (58.7%) elapsed=33.9min ETA=23.9min avg_latency=0.0156s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 132000/221469 (59.6%) elapsed=33.9min ETA=23.0min avg_latency=0.0154s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 134000/221469 (60.5%) elapsed=33.9min ETA=22.1min avg_latency=0.0152s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 136000/221469 (61.4%) elapsed=33.9min ETA=21.3min avg_latency=0.0150s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 138000/221469 (62.3%) elapsed=33.9min ETA=20.5min avg_latency=0.0148s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 140000/221469 (63.2%) elapsed=33.9min ETA=19.7min avg_latency=0.0145s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 142000/221469 (64.1%) elapsed=34.0min ETA=19.0min avg_latency=0.0144s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 144000/221469 (65.0%) elapsed=34.0min ETA=18.3min avg_latency=0.0142s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 146000/221469 (65.9%) elapsed=34.0min ETA=17.6min avg_latency=0.0140s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 148000/221469 (66.8%) elapsed=34.0min ETA=16.9min avg_latency=0.0138s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 150000/221469 (67.7%) elapsed=34.0min ETA=16.2min avg_latency=0.0136s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 152000/221469 (68.6%) elapsed=34.0min ETA=15.5min avg_latency=0.0134s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 154000/221469 (69.5%) elapsed=34.1min ETA=14.9min avg_latency=0.0133s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 156000/221469 (70.4%) elapsed=34.1min ETA=14.3min avg_latency=0.0131s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 158000/221469 (71.3%) elapsed=34.1min ETA=13.7min avg_latency=0.0129s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 160000/221469 (72.2%) elapsed=34.9min ETA=13.4min avg_latency=0.0131s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 162000/221469 (73.1%) elapsed=34.9min ETA=12.8min avg_latency=0.0129s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 164000/221469 (74.1%) elapsed=34.9min ETA=12.2min avg_latency=0.0128s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 166000/221469 (75.0%) elapsed=34.9min ETA=11.7min avg_latency=0.0126s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 168000/221469 (75.9%) elapsed=41.1min ETA=13.1min avg_latency=0.0147s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 170000/221469 (76.8%) elapsed=41.1min ETA=12.4min avg_latency=0.0145s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 172000/221469 (77.7%) elapsed=41.1min ETA=11.8min avg_latency=0.0143s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 174000/221469 (78.6%) elapsed=41.2min ETA=11.2min avg_latency=0.0142s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 176000/221469 (79.5%) elapsed=41.2min ETA=10.6min avg_latency=0.0140s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 178000/221469 (80.4%) elapsed=41.2min ETA=10.1min avg_latency=0.0139s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 180000/221469 (81.3%) elapsed=41.3min ETA=9.5min avg_latency=0.0138s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 182000/221469 (82.2%) elapsed=41.3min ETA=9.0min avg_latency=0.0136s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 184000/221469 (83.1%) elapsed=41.3min ETA=8.4min avg_latency=0.0135s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 186000/221469 (84.0%) elapsed=41.5min ETA=7.9min avg_latency=0.0134s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 188000/221469 (84.9%) elapsed=41.5min ETA=7.4min avg_latency=0.0132s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 190000/221469 (85.8%) elapsed=41.5min ETA=6.9min avg_latency=0.0131s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 192000/221469 (86.7%) elapsed=41.6min ETA=6.4min avg_latency=0.0130s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 194000/221469 (87.6%) elapsed=41.6min ETA=5.9min avg_latency=0.0129s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 196000/221469 (88.5%) elapsed=41.6min ETA=5.4min avg_latency=0.0127s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 198000/221469 (89.4%) elapsed=41.6min ETA=4.9min avg_latency=0.0126s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 200000/221469 (90.3%) elapsed=41.6min ETA=4.5min avg_latency=0.0125s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 202000/221469 (91.2%) elapsed=41.6min ETA=4.0min avg_latency=0.0124s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 204000/221469 (92.1%) elapsed=41.7min ETA=3.6min avg_latency=0.0123s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 206000/221469 (93.0%) elapsed=41.7min ETA=3.1min avg_latency=0.0121s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 208000/221469 (93.9%) elapsed=41.7min ETA=2.7min avg_latency=0.0120s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 210000/221469 (94.8%) elapsed=41.7min ETA=2.3min avg_latency=0.0119s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 212000/221469 (95.7%) elapsed=41.7min ETA=1.9min avg_latency=0.0118s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 214000/221469 (96.6%) elapsed=41.7min ETA=1.5min avg_latency=0.0117s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 216000/221469 (97.5%) elapsed=41.7min ETA=1.1min avg_latency=0.0116s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 218000/221469 (98.4%) elapsed=41.7min ETA=0.7min avg_latency=0.0115s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 220000/221469 (99.3%) elapsed=41.7min ETA=0.3min avg_latency=0.0114s/user
[Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings)] 221469/221469 (100.0%) elapsed=41.7min ETA=0.0min avg_latency=0.0113s/user
✔ Done: Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings) in 41.7min | mean_latency=0.1008s/user | coverage=0.3988

In [18]:
results_df = pd.DataFrame(results)
display(results_df.sort_values(by="ndcg@k", ascending=False))

,model,precision@k,recall@k,map@k,ndcg@k,coverage@k,latency_per_user_s,total_eval_time_s,rmse
2,Content-Based (cosine on embeddings),0.004396,0.021981,0.008380,0.011706,0.0066,0.001219,42.637940,NaN
5,Hybrid SVD++ (session weighting) + Content-Based (cosine on embeddings),0.002379,0.011893,0.004855,0.006559,0.3988,0.100772,2504.196894,NaN
4,SVD++ + session weighting,0.001630,0.008150,0.003988,0.005016,0.4474,0.096419,2395.952253,1.582380
0,NormalPredictor (topN popular candidates),0.001188,0.005942,0.003692,0.004250,0.3148,0.014503,372.947121,1.490790
3,SVD++ basic,0.000278,0.001391,0.000657,0.000836,0.3732,0.092615,2305.661517,0.721007
1,Random recommender,0.000172,0.000858,0.000360,0.000482,1.0000,0.000285,17.989471,NaN

## Interprétation rapide

- **Random recommender** : sert de base sanity-check ; il ignore les préférences et affiche les métriques les plus faibles.
- **NormalPredictor** : exploite la distribution globale des interactions, utile comme baseline non personnalisée mais limitée en couverture personnelle.
- **KNNBasic cosine (item-item)** : capte des co-occurrences simples, efficace quand la popularité locale est un bon signal.
- **SVD++** : modèle factoriel collaboratif qui combine notes implicites et historique d'interactions pour affiner les recommandations.
- **SVD++ + session weighting** : renforce les sessions longues, ce qui peut mieux refléter l'engagement utilisateur pour le contexte news.

---